// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/goverland-labs/goverland-core-storage/internal/proposal (interfaces: DataProvider,Publisher,EventRegistered,DaoProvider,EnsResolver)

// Package proposal is a generated GoMock package.
package proposal

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockDataProvider is a mock of DataProvider interface.
type MockDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDataProviderMockRecorder
}

// MockDataProviderMockRecorder is the mock recorder for MockDataProvider.
type MockDataProviderMockRecorder struct {
	mock *MockDataProvider
}

// NewMockDataProvider creates a new mock instance.
func NewMockDataProvider(ctrl *gomock.Controller) *MockDataProvider {
	mock := &MockDataProvider{ctrl: ctrl}
	mock.recorder = &MockDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataProvider) EXPECT() *MockDataProviderMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataProvider) Create(arg0 Proposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataProviderMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataProvider)(nil).Create), arg0)
}

// GetAvailableForVoting mocks base method.
func (m *MockDataProvider) GetAvailableForVoting(arg0 time.Duration) ([]*Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableForVoting", arg0)
	ret0, _ := ret[0].([]*Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableForVoting indicates an expected call of GetAvailableForVoting.
func (mr *MockDataProviderMockRecorder) GetAvailableForVoting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableForVoting", reflect.TypeOf((*MockDataProvider)(nil).GetAvailableForVoting), arg0)
}

// GetByFilters mocks base method.
func (m *MockDataProvider) GetByFilters(arg0 []Filter) (ProposalList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFilters", arg0)
	ret0, _ := ret[0].(ProposalList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFilters indicates an expected call of GetByFilters.
func (mr *MockDataProviderMockRecorder) GetByFilters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFilters", reflect.TypeOf((*MockDataProvider)(nil).GetByFilters), arg0)
}

// GetByID mocks base method.
func (m *MockDataProvider) GetByID(arg0 string) (*Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(*Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDataProviderMockRecorder) GetByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDataProvider)(nil).GetByID), arg0)
}

// GetTop mocks base method.
func (m *MockDataProvider) GetTop(arg0 []Filter) (ProposalList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop", arg0)
	ret0, _ := ret[0].(ProposalList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop indicates an expected call of GetTop.
func (mr *MockDataProviderMockRecorder) GetTop(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop", reflect.TypeOf((*MockDataProvider)(nil).GetTop), arg0)
}

// Update mocks base method.
func (m *MockDataProvider) Update(arg0 Proposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataProviderMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataProvider)(nil).Update), arg0)
}

// UpdateVotes mocks base method.
func (m *MockDataProvider) UpdateVotes(arg0 []ResolvedAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVotes", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVotes indicates an expected call of UpdateVotes.
func (mr *MockDataProviderMockRecorder) UpdateVotes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVotes", reflect.TypeOf((*MockDataProvider)(nil).UpdateVotes), arg0)
}

// GetSucceededChoices mocks base method.
func (m *MockDataProvider) GetSucceededChoices(arg0 uuid.UUID) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSucceededChoices", arg0)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSucceededChoices indicates an expected call of GetSucceededChoices.
func (mr *MockDataProviderMockRecorder) GetSucceededChoices(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSucceededChoices", reflect.TypeOf((*MockDataProvider)(nil).GetSucceededChoices), arg0)
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishJSON mocks base method.
func (m *MockPublisher) PublishJSON(arg0 context.Context, arg1 string, arg2 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishJSON", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishJSON indicates an expected call of PublishJSON.
func (mr *MockPublisherMockRecorder) PublishJSON(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishJSON", reflect.TypeOf((*MockPublisher)(nil).PublishJSON), arg0, arg1, arg2)
}

// GetTokenPrice mocks base method.
func (m *MockDaoProvider) GetTokenPrice(arg0 uuid.UUID, arg1 int) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenPrice", arg0, arg1)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetTokenPrice indicates an expected call of GetTokenPrice.
func (mr *MockDaoProviderMockRecorder) GetTokenPrice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenPrice", reflect.TypeOf((*MockDaoProvider)(nil).GetTokenPrice), arg0, arg1)
}

// MockEventRegistered is a mock of EventRegistered interface.
type MockEventRegistered struct {
	ctrl     *gomock.Controller
	recorder *MockEventRegisteredMockRecorder
}

// MockEventRegisteredMockRecorder is the mock recorder for MockEventRegistered.
type MockEventRegisteredMockRecorder struct {
	mock *MockEventRegistered
}

// NewMockEventRegistered creates a new mock instance.
func NewMockEventRegistered(ctrl *gomock.Controller) *MockEventRegistered {
	mock := &MockEventRegistered{ctrl: ctrl}
	mock.recorder = &MockEventRegisteredMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRegistered) EXPECT() *MockEventRegisteredMockRecorder {
	return m.recorder
}

// EventExist mocks base method.
func (m *MockEventRegistered) EventExist(arg0 context.Context, arg1, arg2, arg3 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventExist", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventExist indicates an expected call of EventExist.
func (mr *MockEventRegisteredMockRecorder) EventExist(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventExist", reflect.TypeOf((*MockEventRegistered)(nil).EventExist), arg0, arg1, arg2, arg3)
}

// RegisterEvent mocks base method.
func (m *MockEventRegistered) RegisterEvent(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterEvent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterEvent indicates an expected call of RegisterEvent.
func (mr *MockEventRegisteredMockRecorder) RegisterEvent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterEvent", reflect.TypeOf((*MockEventRegistered)(nil).RegisterEvent), arg0, arg1, arg2, arg3)
}

// MockDaoProvider is a mock of DaoProvider interface.
type MockDaoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDaoProviderMockRecorder
}

// MockDaoProviderMockRecorder is the mock recorder for MockDaoProvider.
type MockDaoProviderMockRecorder struct {
	mock *MockDaoProvider
}

// NewMockDaoProvider creates a new mock instance.
func NewMockDaoProvider(ctrl *gomock.Controller) *MockDaoProvider {
	mock := &MockDaoProvider{ctrl: ctrl}
	mock.recorder = &MockDaoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaoProvider) EXPECT() *MockDaoProviderMockRecorder {
	return m.recorder
}

// GetIDByOriginalID mocks base method.
func (m *MockDaoProvider) GetIDByOriginalID(arg0 string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDByOriginalID", arg0)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDByOriginalID indicates an expected call of GetIDByOriginalID.
func (mr *MockDaoProviderMockRecorder) GetIDByOriginalID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDByOriginalID", reflect.TypeOf((*MockDaoProvider)(nil).GetIDByOriginalID), arg0)
}

// MockEnsResolver is a mock of EnsResolver interface.
type MockEnsResolver struct {
	ctrl     *gomock.Controller
	recorder *MockEnsResolverMockRecorder
}

// MockEnsResolverMockRecorder is the mock recorder for MockEnsResolver.
type MockEnsResolverMockRecorder struct {
	mock *MockEnsResolver
}

// NewMockEnsResolver creates a new mock instance.
func NewMockEnsResolver(ctrl *gomock.Controller) *MockEnsResolver {
	mock := &MockEnsResolver{ctrl: ctrl}
	mock.recorder = &MockEnsResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnsResolver) EXPECT() *MockEnsResolverMockRecorder {
	return m.recorder
}

// AddRequests mocks base method.
func (m *MockEnsResolver) AddRequests(arg0 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRequests", arg0)
}

// AddRequests indicates an expected call of AddRequests.
func (mr *MockEnsResolverMockRecorder) AddRequests(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRequests", reflect.TypeOf((*MockEnsResolver)(nil).AddRequests), arg0)
}
