// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: dao.proto

package internalapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DaoClient is the client API for Dao service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaoClient interface {
	GetByID(ctx context.Context, in *DaoByIDRequest, opts ...grpc.CallOption) (*DaoResponse, error)
}

type daoClient struct {
	cc grpc.ClientConnInterface
}

func NewDaoClient(cc grpc.ClientConnInterface) DaoClient {
	return &daoClient{cc}
}

func (c *daoClient) GetByID(ctx context.Context, in *DaoByIDRequest, opts ...grpc.CallOption) (*DaoResponse, error) {
	out := new(DaoResponse)
	err := c.cc.Invoke(ctx, "/internalapi.Dao/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaoServer is the server API for Dao service.
// All implementations must embed UnimplementedDaoServer
// for forward compatibility
type DaoServer interface {
	GetByID(context.Context, *DaoByIDRequest) (*DaoResponse, error)
	mustEmbedUnimplementedDaoServer()
}

// UnimplementedDaoServer must be embedded to have forward compatible implementations.
type UnimplementedDaoServer struct {
}

func (UnimplementedDaoServer) GetByID(context.Context, *DaoByIDRequest) (*DaoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedDaoServer) mustEmbedUnimplementedDaoServer() {}

// UnsafeDaoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaoServer will
// result in compilation errors.
type UnsafeDaoServer interface {
	mustEmbedUnimplementedDaoServer()
}

func RegisterDaoServer(s grpc.ServiceRegistrar, srv DaoServer) {
	s.RegisterService(&Dao_ServiceDesc, srv)
}

func _Dao_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaoByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaoServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internalapi.Dao/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaoServer).GetByID(ctx, req.(*DaoByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dao_ServiceDesc is the grpc.ServiceDesc for Dao service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dao_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalapi.Dao",
	HandlerType: (*DaoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByID",
			Handler:    _Dao_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dao.proto",
}
