// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proposal.proto

package internalapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProposalClient is the client API for Proposal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProposalClient interface {
	GetByID(ctx context.Context, in *ProposalByIDRequest, opts ...grpc.CallOption) (*ProposalByIDResponse, error)
	GetByFilter(ctx context.Context, in *ProposalByFilterRequest, opts ...grpc.CallOption) (*ProposalByFilterResponse, error)
}

type proposalClient struct {
	cc grpc.ClientConnInterface
}

func NewProposalClient(cc grpc.ClientConnInterface) ProposalClient {
	return &proposalClient{cc}
}

func (c *proposalClient) GetByID(ctx context.Context, in *ProposalByIDRequest, opts ...grpc.CallOption) (*ProposalByIDResponse, error) {
	out := new(ProposalByIDResponse)
	err := c.cc.Invoke(ctx, "/internalapi.Proposal/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proposalClient) GetByFilter(ctx context.Context, in *ProposalByFilterRequest, opts ...grpc.CallOption) (*ProposalByFilterResponse, error) {
	out := new(ProposalByFilterResponse)
	err := c.cc.Invoke(ctx, "/internalapi.Proposal/GetByFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProposalServer is the server API for Proposal service.
// All implementations must embed UnimplementedProposalServer
// for forward compatibility
type ProposalServer interface {
	GetByID(context.Context, *ProposalByIDRequest) (*ProposalByIDResponse, error)
	GetByFilter(context.Context, *ProposalByFilterRequest) (*ProposalByFilterResponse, error)
	mustEmbedUnimplementedProposalServer()
}

// UnimplementedProposalServer must be embedded to have forward compatible implementations.
type UnimplementedProposalServer struct {
}

func (UnimplementedProposalServer) GetByID(context.Context, *ProposalByIDRequest) (*ProposalByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedProposalServer) GetByFilter(context.Context, *ProposalByFilterRequest) (*ProposalByFilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByFilter not implemented")
}
func (UnimplementedProposalServer) mustEmbedUnimplementedProposalServer() {}

// UnsafeProposalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProposalServer will
// result in compilation errors.
type UnsafeProposalServer interface {
	mustEmbedUnimplementedProposalServer()
}

func RegisterProposalServer(s grpc.ServiceRegistrar, srv ProposalServer) {
	s.RegisterService(&Proposal_ServiceDesc, srv)
}

func _Proposal_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposalByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internalapi.Proposal/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServer).GetByID(ctx, req.(*ProposalByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proposal_GetByFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposalByFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProposalServer).GetByFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internalapi.Proposal/GetByFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProposalServer).GetByFilter(ctx, req.(*ProposalByFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Proposal_ServiceDesc is the grpc.ServiceDesc for Proposal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proposal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalapi.Proposal",
	HandlerType: (*ProposalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByID",
			Handler:    _Proposal_GetByID_Handler,
		},
		{
			MethodName: "GetByFilter",
			Handler:    _Proposal_GetByFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proposal.proto",
}
