// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: storagepb/dao.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaoByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoId         string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoByIDRequest) Reset() {
	*x = DaoByIDRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoByIDRequest) ProtoMessage() {}

func (x *DaoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoByIDRequest.ProtoReflect.Descriptor instead.
func (*DaoByIDRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{0}
}

func (x *DaoByIDRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type Voting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delay         uint64                 `protobuf:"varint,1,opt,name=delay,proto3" json:"delay,omitempty"`
	Period        uint64                 `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quorum        float32                `protobuf:"fixed32,4,opt,name=quorum,proto3" json:"quorum,omitempty"`
	Blind         bool                   `protobuf:"varint,5,opt,name=blind,proto3" json:"blind,omitempty"`
	HideAbstain   bool                   `protobuf:"varint,6,opt,name=hide_abstain,json=hideAbstain,proto3" json:"hide_abstain,omitempty"`
	Privacy       string                 `protobuf:"bytes,7,opt,name=privacy,proto3" json:"privacy,omitempty"`
	Aliased       bool                   `protobuf:"varint,8,opt,name=aliased,proto3" json:"aliased,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Voting) Reset() {
	*x = Voting{}
	mi := &file_storagepb_dao_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Voting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voting) ProtoMessage() {}

func (x *Voting) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voting.ProtoReflect.Descriptor instead.
func (*Voting) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{1}
}

func (x *Voting) GetDelay() uint64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *Voting) GetPeriod() uint64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Voting) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Voting) GetQuorum() float32 {
	if x != nil {
		return x.Quorum
	}
	return 0
}

func (x *Voting) GetBlind() bool {
	if x != nil {
		return x.Blind
	}
	return false
}

func (x *Voting) GetHideAbstain() bool {
	if x != nil {
		return x.HideAbstain
	}
	return false
}

func (x *Voting) GetPrivacy() string {
	if x != nil {
		return x.Privacy
	}
	return ""
}

func (x *Voting) GetAliased() bool {
	if x != nil {
		return x.Aliased
	}
	return false
}

type Treasury struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Treasury) Reset() {
	*x = Treasury{}
	mi := &file_storagepb_dao_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Treasury) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Treasury) ProtoMessage() {}

func (x *Treasury) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Treasury.ProtoReflect.Descriptor instead.
func (*Treasury) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{2}
}

func (x *Treasury) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Treasury) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Treasury) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type DaoInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Private            bool                   `protobuf:"varint,5,opt,name=private,proto3" json:"private,omitempty"`
	About              string                 `protobuf:"bytes,6,opt,name=about,proto3" json:"about,omitempty"`
	Avatar             string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Terms              string                 `protobuf:"bytes,8,opt,name=terms,proto3" json:"terms,omitempty"`
	Location           string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Website            string                 `protobuf:"bytes,10,opt,name=website,proto3" json:"website,omitempty"`
	Twitter            string                 `protobuf:"bytes,11,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Github             string                 `protobuf:"bytes,12,opt,name=github,proto3" json:"github,omitempty"`
	Coingeko           string                 `protobuf:"bytes,13,opt,name=coingeko,proto3" json:"coingeko,omitempty"`
	Email              string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	Network            string                 `protobuf:"bytes,15,opt,name=network,proto3" json:"network,omitempty"`
	Symbol             string                 `protobuf:"bytes,16,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Skin               string                 `protobuf:"bytes,17,opt,name=skin,proto3" json:"skin,omitempty"`
	Domain             string                 `protobuf:"bytes,18,opt,name=domain,proto3" json:"domain,omitempty"`
	Strategies         []*Strategy            `protobuf:"bytes,19,rep,name=strategies,proto3" json:"strategies,omitempty"`
	Voting             *Voting                `protobuf:"bytes,20,opt,name=voting,proto3" json:"voting,omitempty"`
	Categories         []string               `protobuf:"bytes,21,rep,name=categories,proto3" json:"categories,omitempty"`
	Treasuries         []*Treasury            `protobuf:"bytes,22,rep,name=treasuries,proto3" json:"treasuries,omitempty"`
	FollowersCount     uint64                 `protobuf:"varint,23,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	ProposalsCount     uint64                 `protobuf:"varint,24,opt,name=proposals_count,json=proposalsCount,proto3" json:"proposals_count,omitempty"`
	Guidelines         string                 `protobuf:"bytes,25,opt,name=guidelines,proto3" json:"guidelines,omitempty"`
	Template           string                 `protobuf:"bytes,26,opt,name=template,proto3" json:"template,omitempty"`
	ParentId           string                 `protobuf:"bytes,27,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Alias              string                 `protobuf:"bytes,28,opt,name=alias,proto3" json:"alias,omitempty"`
	ActivitySince      uint64                 `protobuf:"varint,29,opt,name=activity_since,json=activitySince,proto3" json:"activity_since,omitempty"`
	VotersCount        uint64                 `protobuf:"varint,30,opt,name=voters_count,json=votersCount,proto3" json:"voters_count,omitempty"`
	ActiveVotes        uint64                 `protobuf:"varint,31,opt,name=active_votes,json=activeVotes,proto3" json:"active_votes,omitempty"`
	Verified           bool                   `protobuf:"varint,32,opt,name=verified,proto3" json:"verified,omitempty"`
	PopularityIndex    float64                `protobuf:"fixed64,33,opt,name=popularity_index,json=popularityIndex,proto3" json:"popularity_index,omitempty"`
	ActiveProposalsIds []string               `protobuf:"bytes,34,rep,name=active_proposals_ids,json=activeProposalsIds,proto3" json:"active_proposals_ids,omitempty"`
	TokenExist         bool                   `protobuf:"varint,35,opt,name=token_exist,json=tokenExist,proto3" json:"token_exist,omitempty"`
	TokenSymbol        string                 `protobuf:"bytes,36,opt,name=token_symbol,json=tokenSymbol,proto3" json:"token_symbol,omitempty"`
	FungibleId         string                 `protobuf:"bytes,37,opt,name=fungible_id,json=fungibleId,proto3" json:"fungible_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DaoInfo) Reset() {
	*x = DaoInfo{}
	mi := &file_storagepb_dao_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoInfo) ProtoMessage() {}

func (x *DaoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoInfo.ProtoReflect.Descriptor instead.
func (*DaoInfo) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{3}
}

func (x *DaoInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DaoInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DaoInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DaoInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaoInfo) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *DaoInfo) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *DaoInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *DaoInfo) GetTerms() string {
	if x != nil {
		return x.Terms
	}
	return ""
}

func (x *DaoInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *DaoInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *DaoInfo) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

func (x *DaoInfo) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *DaoInfo) GetCoingeko() string {
	if x != nil {
		return x.Coingeko
	}
	return ""
}

func (x *DaoInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DaoInfo) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DaoInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DaoInfo) GetSkin() string {
	if x != nil {
		return x.Skin
	}
	return ""
}

func (x *DaoInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DaoInfo) GetStrategies() []*Strategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

func (x *DaoInfo) GetVoting() *Voting {
	if x != nil {
		return x.Voting
	}
	return nil
}

func (x *DaoInfo) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *DaoInfo) GetTreasuries() []*Treasury {
	if x != nil {
		return x.Treasuries
	}
	return nil
}

func (x *DaoInfo) GetFollowersCount() uint64 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *DaoInfo) GetProposalsCount() uint64 {
	if x != nil {
		return x.ProposalsCount
	}
	return 0
}

func (x *DaoInfo) GetGuidelines() string {
	if x != nil {
		return x.Guidelines
	}
	return ""
}

func (x *DaoInfo) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *DaoInfo) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *DaoInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DaoInfo) GetActivitySince() uint64 {
	if x != nil {
		return x.ActivitySince
	}
	return 0
}

func (x *DaoInfo) GetVotersCount() uint64 {
	if x != nil {
		return x.VotersCount
	}
	return 0
}

func (x *DaoInfo) GetActiveVotes() uint64 {
	if x != nil {
		return x.ActiveVotes
	}
	return 0
}

func (x *DaoInfo) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *DaoInfo) GetPopularityIndex() float64 {
	if x != nil {
		return x.PopularityIndex
	}
	return 0
}

func (x *DaoInfo) GetActiveProposalsIds() []string {
	if x != nil {
		return x.ActiveProposalsIds
	}
	return nil
}

func (x *DaoInfo) GetTokenExist() bool {
	if x != nil {
		return x.TokenExist
	}
	return false
}

func (x *DaoInfo) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *DaoInfo) GetFungibleId() string {
	if x != nil {
		return x.FungibleId
	}
	return ""
}

type DaoByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dao           *DaoInfo               `protobuf:"bytes,1,opt,name=dao,proto3" json:"dao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoByIDResponse) Reset() {
	*x = DaoByIDResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoByIDResponse) ProtoMessage() {}

func (x *DaoByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoByIDResponse.ProtoReflect.Descriptor instead.
func (*DaoByIDResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{4}
}

func (x *DaoByIDResponse) GetDao() *DaoInfo {
	if x != nil {
		return x.Dao
	}
	return nil
}

type DaoByFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *string                `protobuf:"bytes,1,opt,name=query,proto3,oneof" json:"query,omitempty"`
	Category      *string                `protobuf:"bytes,2,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Limit         *uint64                `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint64                `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	DaoIds        []string               `protobuf:"bytes,5,rep,name=dao_ids,json=daoIds,proto3" json:"dao_ids,omitempty"`
	FungibleIds   []string               `protobuf:"bytes,6,rep,name=fungible_ids,json=fungibleIds,proto3" json:"fungible_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoByFilterRequest) Reset() {
	*x = DaoByFilterRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoByFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoByFilterRequest) ProtoMessage() {}

func (x *DaoByFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoByFilterRequest.ProtoReflect.Descriptor instead.
func (*DaoByFilterRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{5}
}

func (x *DaoByFilterRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *DaoByFilterRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *DaoByFilterRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *DaoByFilterRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *DaoByFilterRequest) GetDaoIds() []string {
	if x != nil {
		return x.DaoIds
	}
	return nil
}

func (x *DaoByFilterRequest) GetFungibleIds() []string {
	if x != nil {
		return x.FungibleIds
	}
	return nil
}

type DaoByFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Daos          []*DaoInfo             `protobuf:"bytes,1,rep,name=daos,proto3" json:"daos,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoByFilterResponse) Reset() {
	*x = DaoByFilterResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoByFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoByFilterResponse) ProtoMessage() {}

func (x *DaoByFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoByFilterResponse.ProtoReflect.Descriptor instead.
func (*DaoByFilterResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{6}
}

func (x *DaoByFilterResponse) GetDaos() []*DaoInfo {
	if x != nil {
		return x.Daos
	}
	return nil
}

func (x *DaoByFilterResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TopCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Daos          []*DaoInfo             `protobuf:"bytes,2,rep,name=daos,proto3" json:"daos,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopCategory) Reset() {
	*x = TopCategory{}
	mi := &file_storagepb_dao_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCategory) ProtoMessage() {}

func (x *TopCategory) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCategory.ProtoReflect.Descriptor instead.
func (*TopCategory) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{7}
}

func (x *TopCategory) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TopCategory) GetDaos() []*DaoInfo {
	if x != nil {
		return x.Daos
	}
	return nil
}

func (x *TopCategory) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TopByCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint64                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopByCategoriesRequest) Reset() {
	*x = TopByCategoriesRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopByCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopByCategoriesRequest) ProtoMessage() {}

func (x *TopByCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopByCategoriesRequest.ProtoReflect.Descriptor instead.
func (*TopByCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{8}
}

func (x *TopByCategoriesRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopByCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*TopCategory         `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopByCategoriesResponse) Reset() {
	*x = TopByCategoriesResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopByCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopByCategoriesResponse) ProtoMessage() {}

func (x *TopByCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopByCategoriesResponse.ProtoReflect.Descriptor instead.
func (*TopByCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{9}
}

func (x *TopByCategoriesResponse) GetCategories() []*TopCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetRecommendationsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsListRequest) Reset() {
	*x = GetRecommendationsListRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsListRequest) ProtoMessage() {}

func (x *GetRecommendationsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsListRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsListRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{10}
}

type DaoRecommendationDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalId    string                 `protobuf:"bytes,1,opt,name=original_id,json=originalId,proto3" json:"original_id,omitempty"`
	InternalId    string                 `protobuf:"bytes,2,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	NetworkId     string                 `protobuf:"bytes,5,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoRecommendationDetails) Reset() {
	*x = DaoRecommendationDetails{}
	mi := &file_storagepb_dao_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoRecommendationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoRecommendationDetails) ProtoMessage() {}

func (x *DaoRecommendationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoRecommendationDetails.ProtoReflect.Descriptor instead.
func (*DaoRecommendationDetails) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{11}
}

func (x *DaoRecommendationDetails) GetOriginalId() string {
	if x != nil {
		return x.OriginalId
	}
	return ""
}

func (x *DaoRecommendationDetails) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

func (x *DaoRecommendationDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaoRecommendationDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *DaoRecommendationDetails) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *DaoRecommendationDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetRecommendationsListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	List          []*DaoRecommendationDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsListResponse) Reset() {
	*x = GetRecommendationsListResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsListResponse) ProtoMessage() {}

func (x *GetRecommendationsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsListResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsListResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{12}
}

func (x *GetRecommendationsListResponse) GetList() []*DaoRecommendationDetails {
	if x != nil {
		return x.List
	}
	return nil
}

type TokenInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoId         string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfoRequest) Reset() {
	*x = TokenInfoRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfoRequest) ProtoMessage() {}

func (x *TokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfoRequest.ProtoReflect.Descriptor instead.
func (*TokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{13}
}

func (x *TokenInfoRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type TokenInfoResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Symbol                string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TotalSupply           float64                `protobuf:"fixed64,3,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	CirculatingSupply     float64                `protobuf:"fixed64,4,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	MarketCap             float64                `protobuf:"fixed64,5,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	FullyDilutedValuation float64                `protobuf:"fixed64,6,opt,name=fully_diluted_valuation,json=fullyDilutedValuation,proto3" json:"fully_diluted_valuation,omitempty"`
	Price                 float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	FungibleId            string                 `protobuf:"bytes,8,opt,name=fungible_id,json=fungibleId,proto3" json:"fungible_id,omitempty"`
	Chains                []*TokenChainInfo      `protobuf:"bytes,9,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TokenInfoResponse) Reset() {
	*x = TokenInfoResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfoResponse) ProtoMessage() {}

func (x *TokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfoResponse.ProtoReflect.Descriptor instead.
func (*TokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{14}
}

func (x *TokenInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenInfoResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenInfoResponse) GetTotalSupply() float64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *TokenInfoResponse) GetCirculatingSupply() float64 {
	if x != nil {
		return x.CirculatingSupply
	}
	return 0
}

func (x *TokenInfoResponse) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *TokenInfoResponse) GetFullyDilutedValuation() float64 {
	if x != nil {
		return x.FullyDilutedValuation
	}
	return 0
}

func (x *TokenInfoResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TokenInfoResponse) GetFungibleId() string {
	if x != nil {
		return x.FungibleId
	}
	return ""
}

func (x *TokenInfoResponse) GetChains() []*TokenChainInfo {
	if x != nil {
		return x.Chains
	}
	return nil
}

type TokenChainInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	IconUrl       string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenChainInfo) Reset() {
	*x = TokenChainInfo{}
	mi := &file_storagepb_dao_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenChainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenChainInfo) ProtoMessage() {}

func (x *TokenChainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenChainInfo.ProtoReflect.Descriptor instead.
func (*TokenChainInfo) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{15}
}

func (x *TokenChainInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *TokenChainInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenChainInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenChainInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *TokenChainInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TokenChartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoId         string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenChartRequest) Reset() {
	*x = TokenChartRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenChartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenChartRequest) ProtoMessage() {}

func (x *TokenChartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenChartRequest.ProtoReflect.Descriptor instead.
func (*TokenChartRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{16}
}

func (x *TokenChartRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *TokenChartRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type TokenChartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	PriceChanges  float64                `protobuf:"fixed64,2,opt,name=price_changes,json=priceChanges,proto3" json:"price_changes,omitempty"`
	Points        []*Point               `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenChartResponse) Reset() {
	*x = TokenChartResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenChartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenChartResponse) ProtoMessage() {}

func (x *TokenChartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenChartResponse.ProtoReflect.Descriptor instead.
func (*TokenChartResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{17}
}

func (x *TokenChartResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TokenChartResponse) GetPriceChanges() float64 {
	if x != nil {
		return x.PriceChanges
	}
	return 0
}

func (x *TokenChartResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_storagepb_dao_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{18}
}

func (x *Point) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Point) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type TokenPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoId         string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPricesRequest) Reset() {
	*x = TokenPricesRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPricesRequest) ProtoMessage() {}

func (x *TokenPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPricesRequest.ProtoReflect.Descriptor instead.
func (*TokenPricesRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{19}
}

func (x *TokenPricesRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

type TokenPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPricesResponse) Reset() {
	*x = TokenPricesResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPricesResponse) ProtoMessage() {}

func (x *TokenPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPricesResponse.ProtoReflect.Descriptor instead.
func (*TokenPricesResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{20}
}

func (x *TokenPricesResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateFungibleIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFungibleIdsRequest) Reset() {
	*x = UpdateFungibleIdsRequest{}
	mi := &file_storagepb_dao_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFungibleIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFungibleIdsRequest) ProtoMessage() {}

func (x *UpdateFungibleIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFungibleIdsRequest.ProtoReflect.Descriptor instead.
func (*UpdateFungibleIdsRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateFungibleIdsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateFungibleIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFungibleIdsResponse) Reset() {
	*x = UpdateFungibleIdsResponse{}
	mi := &file_storagepb_dao_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFungibleIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFungibleIdsResponse) ProtoMessage() {}

func (x *UpdateFungibleIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_dao_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFungibleIdsResponse.ProtoReflect.Descriptor instead.
func (*UpdateFungibleIdsResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_dao_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateFungibleIdsResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_storagepb_dao_proto protoreflect.FileDescriptor

const file_storagepb_dao_proto_rawDesc = "" +
	"\n" +
	"\x13storagepb/dao.proto\x12\tstoragepb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14storagepb/base.proto\"'\n" +
	"\x0eDaoByIDRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\"\xcf\x01\n" +
	"\x06Voting\x12\x14\n" +
	"\x05delay\x18\x01 \x01(\x04R\x05delay\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x04R\x06period\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06quorum\x18\x04 \x01(\x02R\x06quorum\x12\x14\n" +
	"\x05blind\x18\x05 \x01(\bR\x05blind\x12!\n" +
	"\fhide_abstain\x18\x06 \x01(\bR\vhideAbstain\x12\x18\n" +
	"\aprivacy\x18\a \x01(\tR\aprivacy\x12\x18\n" +
	"\aaliased\x18\b \x01(\bR\aaliased\"R\n" +
	"\bTreasury\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\"\xba\t\n" +
	"\aDaoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\aprivate\x18\x05 \x01(\bR\aprivate\x12\x14\n" +
	"\x05about\x18\x06 \x01(\tR\x05about\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x14\n" +
	"\x05terms\x18\b \x01(\tR\x05terms\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x18\n" +
	"\awebsite\x18\n" +
	" \x01(\tR\awebsite\x12\x18\n" +
	"\atwitter\x18\v \x01(\tR\atwitter\x12\x16\n" +
	"\x06github\x18\f \x01(\tR\x06github\x12\x1a\n" +
	"\bcoingeko\x18\r \x01(\tR\bcoingeko\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12\x18\n" +
	"\anetwork\x18\x0f \x01(\tR\anetwork\x12\x16\n" +
	"\x06symbol\x18\x10 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04skin\x18\x11 \x01(\tR\x04skin\x12\x16\n" +
	"\x06domain\x18\x12 \x01(\tR\x06domain\x123\n" +
	"\n" +
	"strategies\x18\x13 \x03(\v2\x13.storagepb.StrategyR\n" +
	"strategies\x12)\n" +
	"\x06voting\x18\x14 \x01(\v2\x11.storagepb.VotingR\x06voting\x12\x1e\n" +
	"\n" +
	"categories\x18\x15 \x03(\tR\n" +
	"categories\x123\n" +
	"\n" +
	"treasuries\x18\x16 \x03(\v2\x13.storagepb.TreasuryR\n" +
	"treasuries\x12'\n" +
	"\x0ffollowers_count\x18\x17 \x01(\x04R\x0efollowersCount\x12'\n" +
	"\x0fproposals_count\x18\x18 \x01(\x04R\x0eproposalsCount\x12\x1e\n" +
	"\n" +
	"guidelines\x18\x19 \x01(\tR\n" +
	"guidelines\x12\x1a\n" +
	"\btemplate\x18\x1a \x01(\tR\btemplate\x12\x1b\n" +
	"\tparent_id\x18\x1b \x01(\tR\bparentId\x12\x14\n" +
	"\x05alias\x18\x1c \x01(\tR\x05alias\x12%\n" +
	"\x0eactivity_since\x18\x1d \x01(\x04R\ractivitySince\x12!\n" +
	"\fvoters_count\x18\x1e \x01(\x04R\vvotersCount\x12!\n" +
	"\factive_votes\x18\x1f \x01(\x04R\vactiveVotes\x12\x1a\n" +
	"\bverified\x18  \x01(\bR\bverified\x12)\n" +
	"\x10popularity_index\x18! \x01(\x01R\x0fpopularityIndex\x120\n" +
	"\x14active_proposals_ids\x18\" \x03(\tR\x12activeProposalsIds\x12\x1f\n" +
	"\vtoken_exist\x18# \x01(\bR\n" +
	"tokenExist\x12!\n" +
	"\ftoken_symbol\x18$ \x01(\tR\vtokenSymbol\x12\x1f\n" +
	"\vfungible_id\x18% \x01(\tR\n" +
	"fungibleId\"7\n" +
	"\x0fDaoByIDResponse\x12$\n" +
	"\x03dao\x18\x01 \x01(\v2\x12.storagepb.DaoInfoR\x03dao\"\xf0\x01\n" +
	"\x12DaoByFilterRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tH\x00R\x05query\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x02 \x01(\tH\x01R\bcategory\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x04H\x02R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x04H\x03R\x06offset\x88\x01\x01\x12\x17\n" +
	"\adao_ids\x18\x05 \x03(\tR\x06daoIds\x12!\n" +
	"\ffungible_ids\x18\x06 \x03(\tR\vfungibleIdsB\b\n" +
	"\x06_queryB\v\n" +
	"\t_categoryB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"^\n" +
	"\x13DaoByFilterResponse\x12&\n" +
	"\x04daos\x18\x01 \x03(\v2\x12.storagepb.DaoInfoR\x04daos\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"r\n" +
	"\vTopCategory\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12&\n" +
	"\x04daos\x18\x02 \x03(\v2\x12.storagepb.DaoInfoR\x04daos\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x04R\n" +
	"totalCount\".\n" +
	"\x16TopByCategoriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x04R\x05limit\"Q\n" +
	"\x17TopByCategoriesResponse\x126\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x16.storagepb.TopCategoryR\n" +
	"categories\"\x1f\n" +
	"\x1dGetRecommendationsListRequest\"\xc1\x01\n" +
	"\x18DaoRecommendationDetails\x12\x1f\n" +
	"\voriginal_id\x18\x01 \x01(\tR\n" +
	"originalId\x12\x1f\n" +
	"\vinternal_id\x18\x02 \x01(\tR\n" +
	"internalId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"network_id\x18\x05 \x01(\tR\tnetworkId\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\"Y\n" +
	"\x1eGetRecommendationsListResponse\x127\n" +
	"\x04list\x18\x01 \x03(\v2#.storagepb.DaoRecommendationDetailsR\x04list\")\n" +
	"\x10TokenInfoRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\"\xd2\x02\n" +
	"\x11TokenInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12!\n" +
	"\ftotal_supply\x18\x03 \x01(\x01R\vtotalSupply\x12-\n" +
	"\x12circulating_supply\x18\x04 \x01(\x01R\x11circulatingSupply\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x05 \x01(\x01R\tmarketCap\x126\n" +
	"\x17fully_diluted_valuation\x18\x06 \x01(\x01R\x15fullyDilutedValuation\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1f\n" +
	"\vfungible_id\x18\b \x01(\tR\n" +
	"fungibleId\x121\n" +
	"\x06chains\x18\t \x03(\v2\x19.storagepb.TokenChainInfoR\x06chains\"\x90\x01\n" +
	"\x0eTokenChainInfo\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"B\n" +
	"\x11TokenChartRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"y\n" +
	"\x12TokenChartResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12#\n" +
	"\rprice_changes\x18\x02 \x01(\x01R\fpriceChanges\x12(\n" +
	"\x06points\x18\x03 \x03(\v2\x10.storagepb.PointR\x06points\"M\n" +
	"\x05Point\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"+\n" +
	"\x12TokenPricesRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\"-\n" +
	"\x13TokenPricesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"6\n" +
	"\x18UpdateFungibleIdsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"3\n" +
	"\x19UpdateFungibleIdsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xb0\x05\n" +
	"\x03Dao\x12@\n" +
	"\aGetByID\x12\x19.storagepb.DaoByIDRequest\x1a\x1a.storagepb.DaoByIDResponse\x12L\n" +
	"\vGetByFilter\x12\x1d.storagepb.DaoByFilterRequest\x1a\x1e.storagepb.DaoByFilterResponse\x12[\n" +
	"\x12GetTopByCategories\x12!.storagepb.TopByCategoriesRequest\x1a\".storagepb.TopByCategoriesResponse\x12m\n" +
	"\x16GetRecommendationsList\x12(.storagepb.GetRecommendationsListRequest\x1a).storagepb.GetRecommendationsListResponse\x12I\n" +
	"\fGetTokenInfo\x12\x1b.storagepb.TokenInfoRequest\x1a\x1c.storagepb.TokenInfoResponse\x12L\n" +
	"\rGetTokenChart\x12\x1c.storagepb.TokenChartRequest\x1a\x1d.storagepb.TokenChartResponse\x12T\n" +
	"\x13PopulateTokenPrices\x12\x1d.storagepb.TokenPricesRequest\x1a\x1e.storagepb.TokenPricesResponse\x12^\n" +
	"\x11UpdateFungibleIds\x12#.storagepb.UpdateFungibleIdsRequest\x1a$.storagepb.UpdateFungibleIdsResponseB\rZ\v.;storagepbb\x06proto3"

var (
	file_storagepb_dao_proto_rawDescOnce sync.Once
	file_storagepb_dao_proto_rawDescData []byte
)

func file_storagepb_dao_proto_rawDescGZIP() []byte {
	file_storagepb_dao_proto_rawDescOnce.Do(func() {
		file_storagepb_dao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storagepb_dao_proto_rawDesc), len(file_storagepb_dao_proto_rawDesc)))
	})
	return file_storagepb_dao_proto_rawDescData
}

var file_storagepb_dao_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_storagepb_dao_proto_goTypes = []any{
	(*DaoByIDRequest)(nil),                 // 0: storagepb.DaoByIDRequest
	(*Voting)(nil),                         // 1: storagepb.Voting
	(*Treasury)(nil),                       // 2: storagepb.Treasury
	(*DaoInfo)(nil),                        // 3: storagepb.DaoInfo
	(*DaoByIDResponse)(nil),                // 4: storagepb.DaoByIDResponse
	(*DaoByFilterRequest)(nil),             // 5: storagepb.DaoByFilterRequest
	(*DaoByFilterResponse)(nil),            // 6: storagepb.DaoByFilterResponse
	(*TopCategory)(nil),                    // 7: storagepb.TopCategory
	(*TopByCategoriesRequest)(nil),         // 8: storagepb.TopByCategoriesRequest
	(*TopByCategoriesResponse)(nil),        // 9: storagepb.TopByCategoriesResponse
	(*GetRecommendationsListRequest)(nil),  // 10: storagepb.GetRecommendationsListRequest
	(*DaoRecommendationDetails)(nil),       // 11: storagepb.DaoRecommendationDetails
	(*GetRecommendationsListResponse)(nil), // 12: storagepb.GetRecommendationsListResponse
	(*TokenInfoRequest)(nil),               // 13: storagepb.TokenInfoRequest
	(*TokenInfoResponse)(nil),              // 14: storagepb.TokenInfoResponse
	(*TokenChainInfo)(nil),                 // 15: storagepb.TokenChainInfo
	(*TokenChartRequest)(nil),              // 16: storagepb.TokenChartRequest
	(*TokenChartResponse)(nil),             // 17: storagepb.TokenChartResponse
	(*Point)(nil),                          // 18: storagepb.Point
	(*TokenPricesRequest)(nil),             // 19: storagepb.TokenPricesRequest
	(*TokenPricesResponse)(nil),            // 20: storagepb.TokenPricesResponse
	(*UpdateFungibleIdsRequest)(nil),       // 21: storagepb.UpdateFungibleIdsRequest
	(*UpdateFungibleIdsResponse)(nil),      // 22: storagepb.UpdateFungibleIdsResponse
	(*timestamppb.Timestamp)(nil),          // 23: google.protobuf.Timestamp
	(*Strategy)(nil),                       // 24: storagepb.Strategy
}
var file_storagepb_dao_proto_depIdxs = []int32{
	23, // 0: storagepb.DaoInfo.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: storagepb.DaoInfo.updated_at:type_name -> google.protobuf.Timestamp
	24, // 2: storagepb.DaoInfo.strategies:type_name -> storagepb.Strategy
	1,  // 3: storagepb.DaoInfo.voting:type_name -> storagepb.Voting
	2,  // 4: storagepb.DaoInfo.treasuries:type_name -> storagepb.Treasury
	3,  // 5: storagepb.DaoByIDResponse.dao:type_name -> storagepb.DaoInfo
	3,  // 6: storagepb.DaoByFilterResponse.daos:type_name -> storagepb.DaoInfo
	3,  // 7: storagepb.TopCategory.daos:type_name -> storagepb.DaoInfo
	7,  // 8: storagepb.TopByCategoriesResponse.categories:type_name -> storagepb.TopCategory
	11, // 9: storagepb.GetRecommendationsListResponse.list:type_name -> storagepb.DaoRecommendationDetails
	15, // 10: storagepb.TokenInfoResponse.chains:type_name -> storagepb.TokenChainInfo
	18, // 11: storagepb.TokenChartResponse.points:type_name -> storagepb.Point
	23, // 12: storagepb.Point.time:type_name -> google.protobuf.Timestamp
	0,  // 13: storagepb.Dao.GetByID:input_type -> storagepb.DaoByIDRequest
	5,  // 14: storagepb.Dao.GetByFilter:input_type -> storagepb.DaoByFilterRequest
	8,  // 15: storagepb.Dao.GetTopByCategories:input_type -> storagepb.TopByCategoriesRequest
	10, // 16: storagepb.Dao.GetRecommendationsList:input_type -> storagepb.GetRecommendationsListRequest
	13, // 17: storagepb.Dao.GetTokenInfo:input_type -> storagepb.TokenInfoRequest
	16, // 18: storagepb.Dao.GetTokenChart:input_type -> storagepb.TokenChartRequest
	19, // 19: storagepb.Dao.PopulateTokenPrices:input_type -> storagepb.TokenPricesRequest
	21, // 20: storagepb.Dao.UpdateFungibleIds:input_type -> storagepb.UpdateFungibleIdsRequest
	4,  // 21: storagepb.Dao.GetByID:output_type -> storagepb.DaoByIDResponse
	6,  // 22: storagepb.Dao.GetByFilter:output_type -> storagepb.DaoByFilterResponse
	9,  // 23: storagepb.Dao.GetTopByCategories:output_type -> storagepb.TopByCategoriesResponse
	12, // 24: storagepb.Dao.GetRecommendationsList:output_type -> storagepb.GetRecommendationsListResponse
	14, // 25: storagepb.Dao.GetTokenInfo:output_type -> storagepb.TokenInfoResponse
	17, // 26: storagepb.Dao.GetTokenChart:output_type -> storagepb.TokenChartResponse
	20, // 27: storagepb.Dao.PopulateTokenPrices:output_type -> storagepb.TokenPricesResponse
	22, // 28: storagepb.Dao.UpdateFungibleIds:output_type -> storagepb.UpdateFungibleIdsResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_storagepb_dao_proto_init() }
func file_storagepb_dao_proto_init() {
	if File_storagepb_dao_proto != nil {
		return
	}
	file_storagepb_base_proto_init()
	file_storagepb_dao_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storagepb_dao_proto_rawDesc), len(file_storagepb_dao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storagepb_dao_proto_goTypes,
		DependencyIndexes: file_storagepb_dao_proto_depIdxs,
		MessageInfos:      file_storagepb_dao_proto_msgTypes,
	}.Build()
	File_storagepb_dao_proto = out.File
	file_storagepb_dao_proto_goTypes = nil
	file_storagepb_dao_proto_depIdxs = nil
}
