// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: storagepb/delegate.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DelegationType int32

const (
	DelegationType_DELEGATION_TYPE_UNSPECIFIED      DelegationType = 0
	DelegationType_DELEGATION_TYPE_SPLIT_DELEGATION DelegationType = 1
	DelegationType_DELEGATION_TYPE_DELEGATION       DelegationType = 2
	DelegationType_DELEGATION_TYPE_ERC20_VOTES      DelegationType = 3
	DelegationType_DELEGATION_TYPE_UNRECOGNIZED     DelegationType = 4
)

// Enum value maps for DelegationType.
var (
	DelegationType_name = map[int32]string{
		0: "DELEGATION_TYPE_UNSPECIFIED",
		1: "DELEGATION_TYPE_SPLIT_DELEGATION",
		2: "DELEGATION_TYPE_DELEGATION",
		3: "DELEGATION_TYPE_ERC20_VOTES",
		4: "DELEGATION_TYPE_UNRECOGNIZED",
	}
	DelegationType_value = map[string]int32{
		"DELEGATION_TYPE_UNSPECIFIED":      0,
		"DELEGATION_TYPE_SPLIT_DELEGATION": 1,
		"DELEGATION_TYPE_DELEGATION":       2,
		"DELEGATION_TYPE_ERC20_VOTES":      3,
		"DELEGATION_TYPE_UNRECOGNIZED":     4,
	}
)

func (x DelegationType) Enum() *DelegationType {
	p := new(DelegationType)
	*p = x
	return p
}

func (x DelegationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DelegationType) Descriptor() protoreflect.EnumDescriptor {
	return file_storagepb_delegate_proto_enumTypes[0].Descriptor()
}

func (DelegationType) Type() protoreflect.EnumType {
	return &file_storagepb_delegate_proto_enumTypes[0]
}

func (x DelegationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DelegationType.Descriptor instead.
func (DelegationType) EnumDescriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{0}
}

type GetDelegatesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DaoId          string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	QueryAccounts  []string               `protobuf:"bytes,2,rep,name=query_accounts,json=queryAccounts,proto3" json:"query_accounts,omitempty"`
	Sort           *string                `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	DelegationType *DelegationType        `protobuf:"varint,6,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType,oneof" json:"delegation_type,omitempty"`
	ChainId        *string                `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDelegatesRequest) Reset() {
	*x = GetDelegatesRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesRequest) ProtoMessage() {}

func (x *GetDelegatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesRequest.ProtoReflect.Descriptor instead.
func (*GetDelegatesRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{0}
}

func (x *GetDelegatesRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *GetDelegatesRequest) GetQueryAccounts() []string {
	if x != nil {
		return x.QueryAccounts
	}
	return nil
}

func (x *GetDelegatesRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *GetDelegatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDelegatesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetDelegatesRequest) GetDelegationType() DelegationType {
	if x != nil && x.DelegationType != nil {
		return *x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *GetDelegatesRequest) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

type GetDelegatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegates     []*DelegateEntry       `protobuf:"bytes,1,rep,name=delegates,proto3" json:"delegates,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesResponse) Reset() {
	*x = GetDelegatesResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesResponse) ProtoMessage() {}

func (x *GetDelegatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesResponse.ProtoReflect.Descriptor instead.
func (*GetDelegatesResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{1}
}

func (x *GetDelegatesResponse) GetDelegates() []*DelegateEntry {
	if x != nil {
		return x.Delegates
	}
	return nil
}

func (x *GetDelegatesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DelegateEntry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Address               string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	EnsName               string                 `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	DelegatorCount        int32                  `protobuf:"varint,3,opt,name=delegator_count,json=delegatorCount,proto3" json:"delegator_count,omitempty"`
	PercentOfDelegators   float64                `protobuf:"fixed64,4,opt,name=percent_of_delegators,json=percentOfDelegators,proto3" json:"percent_of_delegators,omitempty"` // in basis points
	VotingPower           float64                `protobuf:"fixed64,5,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	PercentOfVotingPower  float64                `protobuf:"fixed64,6,opt,name=percent_of_voting_power,json=percentOfVotingPower,proto3" json:"percent_of_voting_power,omitempty"` // in basis points
	About                 string                 `protobuf:"bytes,7,opt,name=about,proto3" json:"about,omitempty"`
	Statement             string                 `protobuf:"bytes,8,opt,name=statement,proto3" json:"statement,omitempty"`
	VotesCount            int32                  `protobuf:"varint,9,opt,name=votes_count,json=votesCount,proto3" json:"votes_count,omitempty"`
	CreatedProposalsCount int32                  `protobuf:"varint,10,opt,name=created_proposals_count,json=createdProposalsCount,proto3" json:"created_proposals_count,omitempty"`
	DelegationType        DelegationType         `protobuf:"varint,11,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	ChainId               *string                `protobuf:"bytes,12,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DelegateEntry) Reset() {
	*x = DelegateEntry{}
	mi := &file_storagepb_delegate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateEntry) ProtoMessage() {}

func (x *DelegateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateEntry.ProtoReflect.Descriptor instead.
func (*DelegateEntry) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{2}
}

func (x *DelegateEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DelegateEntry) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *DelegateEntry) GetDelegatorCount() int32 {
	if x != nil {
		return x.DelegatorCount
	}
	return 0
}

func (x *DelegateEntry) GetPercentOfDelegators() float64 {
	if x != nil {
		return x.PercentOfDelegators
	}
	return 0
}

func (x *DelegateEntry) GetVotingPower() float64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *DelegateEntry) GetPercentOfVotingPower() float64 {
	if x != nil {
		return x.PercentOfVotingPower
	}
	return 0
}

func (x *DelegateEntry) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *DelegateEntry) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *DelegateEntry) GetVotesCount() int32 {
	if x != nil {
		return x.VotesCount
	}
	return 0
}

func (x *DelegateEntry) GetCreatedProposalsCount() int32 {
	if x != nil {
		return x.CreatedProposalsCount
	}
	return 0
}

func (x *DelegateEntry) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *DelegateEntry) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

type DelegatorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	EnsName       string                 `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	TokenValue    string                 `protobuf:"bytes,5,opt,name=token_value,json=tokenValue,proto3" json:"token_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegatorEntry) Reset() {
	*x = DelegatorEntry{}
	mi := &file_storagepb_delegate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegatorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegatorEntry) ProtoMessage() {}

func (x *DelegatorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegatorEntry.ProtoReflect.Descriptor instead.
func (*DelegatorEntry) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{3}
}

func (x *DelegatorEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DelegatorEntry) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *DelegatorEntry) GetTokenValue() string {
	if x != nil {
		return x.TokenValue
	}
	return ""
}

type GetDelegateProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DaoId          string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	DelegationType DelegationType         `protobuf:"varint,3,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	ChainId        *string                `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDelegateProfileRequest) Reset() {
	*x = GetDelegateProfileRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegateProfileRequest) ProtoMessage() {}

func (x *GetDelegateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegateProfileRequest.ProtoReflect.Descriptor instead.
func (*GetDelegateProfileRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{4}
}

func (x *GetDelegateProfileRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *GetDelegateProfileRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDelegateProfileRequest) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *GetDelegateProfileRequest) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

type GetDelegateProfileResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Address              string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	VotingPower          float64                `protobuf:"fixed64,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	IncomingPower        float64                `protobuf:"fixed64,3,opt,name=incoming_power,json=incomingPower,proto3" json:"incoming_power,omitempty"`
	OutgoingPower        float64                `protobuf:"fixed64,4,opt,name=outgoing_power,json=outgoingPower,proto3" json:"outgoing_power,omitempty"`
	PercentOfVotingPower float64                `protobuf:"fixed64,5,opt,name=percent_of_voting_power,json=percentOfVotingPower,proto3" json:"percent_of_voting_power,omitempty"`
	PercentOfDelegators  float64                `protobuf:"fixed64,6,opt,name=percent_of_delegators,json=percentOfDelegators,proto3" json:"percent_of_delegators,omitempty"`
	Delegates            []*ProfileDelegateItem `protobuf:"bytes,7,rep,name=delegates,proto3" json:"delegates,omitempty"`
	Expiration           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetDelegateProfileResponse) Reset() {
	*x = GetDelegateProfileResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegateProfileResponse) ProtoMessage() {}

func (x *GetDelegateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegateProfileResponse.ProtoReflect.Descriptor instead.
func (*GetDelegateProfileResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{5}
}

func (x *GetDelegateProfileResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDelegateProfileResponse) GetVotingPower() float64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetIncomingPower() float64 {
	if x != nil {
		return x.IncomingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetOutgoingPower() float64 {
	if x != nil {
		return x.OutgoingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetPercentOfVotingPower() float64 {
	if x != nil {
		return x.PercentOfVotingPower
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetPercentOfDelegators() float64 {
	if x != nil {
		return x.PercentOfDelegators
	}
	return 0
}

func (x *GetDelegateProfileResponse) GetDelegates() []*ProfileDelegateItem {
	if x != nil {
		return x.Delegates
	}
	return nil
}

func (x *GetDelegateProfileResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type ProfileDelegateItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	EnsName        string                 `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	Weight         float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	DelegatedPower float64                `protobuf:"fixed64,4,opt,name=delegated_power,json=delegatedPower,proto3" json:"delegated_power,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileDelegateItem) Reset() {
	*x = ProfileDelegateItem{}
	mi := &file_storagepb_delegate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileDelegateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDelegateItem) ProtoMessage() {}

func (x *ProfileDelegateItem) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileDelegateItem.ProtoReflect.Descriptor instead.
func (*ProfileDelegateItem) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileDelegateItem) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProfileDelegateItem) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *ProfileDelegateItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProfileDelegateItem) GetDelegatedPower() float64 {
	if x != nil {
		return x.DelegatedPower
	}
	return 0
}

type GetTopDelegatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account address that initiates the delegation
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatesRequest) Reset() {
	*x = GetTopDelegatesRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatesRequest) ProtoMessage() {}

func (x *GetTopDelegatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatesRequest.ProtoReflect.Descriptor instead.
func (*GetTopDelegatesRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{7}
}

func (x *GetTopDelegatesRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DelegationDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The delegation address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Resolved ens name
	EnsName string `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	// Percentage of delegation
	PercentOfDelegators int32 `protobuf:"varint,3,opt,name=percent_of_delegators,json=percentOfDelegators,proto3" json:"percent_of_delegators,omitempty"`
	// Expires at date. If 0 the expiration is not set
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationDetails) Reset() {
	*x = DelegationDetails{}
	mi := &file_storagepb_delegate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationDetails) ProtoMessage() {}

func (x *DelegationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationDetails.ProtoReflect.Descriptor instead.
func (*DelegationDetails) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{8}
}

func (x *DelegationDetails) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DelegationDetails) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *DelegationDetails) GetPercentOfDelegators() int32 {
	if x != nil {
		return x.PercentOfDelegators
	}
	return 0
}

func (x *DelegationDetails) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type DelegatesSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dao details
	Dao *DaoInfo `protobuf:"bytes,1,opt,name=dao,proto3" json:"dao,omitempty"`
	// List of delegates
	List []*DelegationDetails `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	// number of delegations in this DAO
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegatesSummary) Reset() {
	*x = DelegatesSummary{}
	mi := &file_storagepb_delegate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegatesSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegatesSummary) ProtoMessage() {}

func (x *DelegatesSummary) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegatesSummary.ProtoReflect.Descriptor instead.
func (*DelegatesSummary) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{9}
}

func (x *DelegatesSummary) GetDao() *DaoInfo {
	if x != nil {
		return x.Dao
	}
	return nil
}

func (x *DelegatesSummary) GetList() []*DelegationDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *DelegatesSummary) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetTopDelegatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of total delegations in our DB
	TotalDelegatesCount int32 `protobuf:"varint,1,opt,name=total_delegates_count,json=totalDelegatesCount,proto3" json:"total_delegates_count,omitempty"`
	// List of delegates grouped by dao and sorted by popularity index
	List          []*DelegatesSummary `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatesResponse) Reset() {
	*x = GetTopDelegatesResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatesResponse) ProtoMessage() {}

func (x *GetTopDelegatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatesResponse.ProtoReflect.Descriptor instead.
func (*GetTopDelegatesResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{10}
}

func (x *GetTopDelegatesResponse) GetTotalDelegatesCount() int32 {
	if x != nil {
		return x.TotalDelegatesCount
	}
	return 0
}

func (x *GetTopDelegatesResponse) GetList() []*DelegatesSummary {
	if x != nil {
		return x.List
	}
	return nil
}

type GetTopDelegatorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account address that initiates the delegation
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatorsRequest) Reset() {
	*x = GetTopDelegatorsRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatorsRequest) ProtoMessage() {}

func (x *GetTopDelegatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatorsRequest.ProtoReflect.Descriptor instead.
func (*GetTopDelegatorsRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{11}
}

func (x *GetTopDelegatorsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DelegatorSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dao details
	Dao *DaoInfo `protobuf:"bytes,1,opt,name=dao,proto3" json:"dao,omitempty"`
	// List of delegators
	List []*DelegationDetails `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	// number of delegators in this DAO
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegatorSummary) Reset() {
	*x = DelegatorSummary{}
	mi := &file_storagepb_delegate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegatorSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegatorSummary) ProtoMessage() {}

func (x *DelegatorSummary) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegatorSummary.ProtoReflect.Descriptor instead.
func (*DelegatorSummary) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{12}
}

func (x *DelegatorSummary) GetDao() *DaoInfo {
	if x != nil {
		return x.Dao
	}
	return nil
}

func (x *DelegatorSummary) GetList() []*DelegationDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *DelegatorSummary) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetTopDelegatorsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of total delegators in our DB
	TotalDelegatorsCount int32 `protobuf:"varint,1,opt,name=total_delegators_count,json=totalDelegatorsCount,proto3" json:"total_delegators_count,omitempty"`
	// List of delegators grouped by dao and sorted by popularity index
	List          []*DelegatorSummary `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatorsResponse) Reset() {
	*x = GetTopDelegatorsResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatorsResponse) ProtoMessage() {}

func (x *GetTopDelegatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatorsResponse.ProtoReflect.Descriptor instead.
func (*GetTopDelegatorsResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{13}
}

func (x *GetTopDelegatorsResponse) GetTotalDelegatorsCount() int32 {
	if x != nil {
		return x.TotalDelegatorsCount
	}
	return 0
}

func (x *GetTopDelegatorsResponse) GetList() []*DelegatorSummary {
	if x != nil {
		return x.List
	}
	return nil
}

type GetDelegationSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account address that initiates the delegation
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegationSummaryRequest) Reset() {
	*x = GetDelegationSummaryRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegationSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegationSummaryRequest) ProtoMessage() {}

func (x *GetDelegationSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegationSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDelegationSummaryRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{14}
}

func (x *GetDelegationSummaryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetDelegationSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of total delegators in our DB
	TotalDelegatorsCount int32 `protobuf:"varint,1,opt,name=total_delegators_count,json=totalDelegatorsCount,proto3" json:"total_delegators_count,omitempty"`
	// The number of total delegates in our DB
	TotalDelegatesCount int32 `protobuf:"varint,2,opt,name=total_delegates_count,json=totalDelegatesCount,proto3" json:"total_delegates_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetDelegationSummaryResponse) Reset() {
	*x = GetDelegationSummaryResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegationSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegationSummaryResponse) ProtoMessage() {}

func (x *GetDelegationSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegationSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetDelegationSummaryResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{15}
}

func (x *GetDelegationSummaryResponse) GetTotalDelegatorsCount() int32 {
	if x != nil {
		return x.TotalDelegatorsCount
	}
	return 0
}

func (x *GetDelegationSummaryResponse) GetTotalDelegatesCount() int32 {
	if x != nil {
		return x.TotalDelegatesCount
	}
	return 0
}

type GetDelegatesByDaoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	DaoId string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	// The account address that initiates the delegation
	Address       string  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Limit         uint32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        *uint32 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesByDaoRequest) Reset() {
	*x = GetDelegatesByDaoRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesByDaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesByDaoRequest) ProtoMessage() {}

func (x *GetDelegatesByDaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesByDaoRequest.ProtoReflect.Descriptor instead.
func (*GetDelegatesByDaoRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{16}
}

func (x *GetDelegatesByDaoRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *GetDelegatesByDaoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDelegatesByDaoRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDelegatesByDaoRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetDelegatesByDaoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of delegates
	List []*DelegationDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// number of delegations in this DAO
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesByDaoResponse) Reset() {
	*x = GetDelegatesByDaoResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesByDaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesByDaoResponse) ProtoMessage() {}

func (x *GetDelegatesByDaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesByDaoResponse.ProtoReflect.Descriptor instead.
func (*GetDelegatesByDaoResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{17}
}

func (x *GetDelegatesByDaoResponse) GetList() []*DelegationDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetDelegatesByDaoResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetDelegatorsByDaoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	DaoId string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	// The account address that initiates the delegation
	Address       string  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Limit         uint32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        *uint32 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatorsByDaoRequest) Reset() {
	*x = GetDelegatorsByDaoRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatorsByDaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatorsByDaoRequest) ProtoMessage() {}

func (x *GetDelegatorsByDaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatorsByDaoRequest.ProtoReflect.Descriptor instead.
func (*GetDelegatorsByDaoRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{18}
}

func (x *GetDelegatorsByDaoRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *GetDelegatorsByDaoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDelegatorsByDaoRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDelegatorsByDaoRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetDelegatorsByDaoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of delegators
	List []*DelegationDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// number of delegators in this DAO
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatorsByDaoResponse) Reset() {
	*x = GetDelegatorsByDaoResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatorsByDaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatorsByDaoResponse) ProtoMessage() {}

func (x *GetDelegatorsByDaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatorsByDaoResponse.ProtoReflect.Descriptor instead.
func (*GetDelegatorsByDaoResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{19}
}

func (x *GetDelegatorsByDaoResponse) GetList() []*DelegationDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetDelegatorsByDaoResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetDelegatorsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DaoId          string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	ChainId        string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Limit          uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         *uint32                `protobuf:"varint,5,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	DelegationType DelegationType         `protobuf:"varint,6,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDelegatorsRequest) Reset() {
	*x = GetDelegatorsRequest{}
	mi := &file_storagepb_delegate_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatorsRequest) ProtoMessage() {}

func (x *GetDelegatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatorsRequest.ProtoReflect.Descriptor instead.
func (*GetDelegatorsRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{20}
}

func (x *GetDelegatorsRequest) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *GetDelegatorsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetDelegatorsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDelegatorsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDelegatorsRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetDelegatorsRequest) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

type GetDelegatorsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of delegators
	List []*DelegatorEntry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// number of delegators in this DAO
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatorsResponse) Reset() {
	*x = GetDelegatorsResponse{}
	mi := &file_storagepb_delegate_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatorsResponse) ProtoMessage() {}

func (x *GetDelegatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatorsResponse.ProtoReflect.Descriptor instead.
func (*GetDelegatorsResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{21}
}

func (x *GetDelegatorsResponse) GetList() []*DelegatorEntry {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetDelegatorsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// V2 implementation
type GetDelegatesV2Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DaoId          string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	QueryAccounts  []string               `protobuf:"bytes,2,rep,name=query_accounts,json=queryAccounts,proto3" json:"query_accounts,omitempty"`
	Sort           *string                `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	DelegationType DelegationType         `protobuf:"varint,6,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	ChainId        *string                `protobuf:"bytes,7,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDelegatesV2Request) Reset() {
	*x = GetDelegatesV2Request{}
	mi := &file_storagepb_delegate_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesV2Request) ProtoMessage() {}

func (x *GetDelegatesV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesV2Request.ProtoReflect.Descriptor instead.
func (*GetDelegatesV2Request) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{22}
}

func (x *GetDelegatesV2Request) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *GetDelegatesV2Request) GetQueryAccounts() []string {
	if x != nil {
		return x.QueryAccounts
	}
	return nil
}

func (x *GetDelegatesV2Request) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *GetDelegatesV2Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDelegatesV2Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetDelegatesV2Request) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *GetDelegatesV2Request) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

type TokenValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      int32                  `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValue) Reset() {
	*x = TokenValue{}
	mi := &file_storagepb_delegate_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValue) ProtoMessage() {}

func (x *TokenValue) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValue.ProtoReflect.Descriptor instead.
func (*TokenValue) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{23}
}

func (x *TokenValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TokenValue) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenValue) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

// Unified structure for delegation entry (split-delegation/erc20-votes)
type DelegateEntryV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The delegation address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Resolved ens name
	EnsName        string `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	DelegatorCount *int32 `protobuf:"varint,3,opt,name=delegator_count,json=delegatorCount,proto3,oneof" json:"delegator_count,omitempty"`
	// Percentage of delegation in basis points
	PercentOfDelegators *float64 `protobuf:"fixed64,4,opt,name=percent_of_delegators,json=percentOfDelegators,proto3,oneof" json:"percent_of_delegators,omitempty"`
	// Percentage of voting power in basis points
	PercentOfVotingPower *float64 `protobuf:"fixed64,5,opt,name=percent_of_voting_power,json=percentOfVotingPower,proto3,oneof" json:"percent_of_voting_power,omitempty"`
	// Text description
	About *string `protobuf:"bytes,6,opt,name=about,proto3,oneof" json:"about,omitempty"`
	// Text description
	Statement *string `protobuf:"bytes,7,opt,name=statement,proto3,oneof" json:"statement,omitempty"`
	// Total votes in our DB
	VotesCount *int32 `protobuf:"varint,8,opt,name=votes_count,json=votesCount,proto3,oneof" json:"votes_count,omitempty"`
	// Total proposals in our DB
	CreatedProposalsCount *int32 `protobuf:"varint,9,opt,name=created_proposals_count,json=createdProposalsCount,proto3,oneof" json:"created_proposals_count,omitempty"`
	// Delegation value is different for delegation types
	// for split-delegation
	VotingPower *float64 `protobuf:"fixed64,10,opt,name=voting_power,json=votingPower,proto3,oneof" json:"voting_power,omitempty"`
	// for erc20-votes
	TokenValue *TokenValue `protobuf:"bytes,11,opt,name=token_value,json=tokenValue,proto3,oneof" json:"token_value,omitempty"`
	// Expires at date. If 0 the expiration is not set
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegateEntryV2) Reset() {
	*x = DelegateEntryV2{}
	mi := &file_storagepb_delegate_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateEntryV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateEntryV2) ProtoMessage() {}

func (x *DelegateEntryV2) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateEntryV2.ProtoReflect.Descriptor instead.
func (*DelegateEntryV2) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{24}
}

func (x *DelegateEntryV2) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DelegateEntryV2) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *DelegateEntryV2) GetDelegatorCount() int32 {
	if x != nil && x.DelegatorCount != nil {
		return *x.DelegatorCount
	}
	return 0
}

func (x *DelegateEntryV2) GetPercentOfDelegators() float64 {
	if x != nil && x.PercentOfDelegators != nil {
		return *x.PercentOfDelegators
	}
	return 0
}

func (x *DelegateEntryV2) GetPercentOfVotingPower() float64 {
	if x != nil && x.PercentOfVotingPower != nil {
		return *x.PercentOfVotingPower
	}
	return 0
}

func (x *DelegateEntryV2) GetAbout() string {
	if x != nil && x.About != nil {
		return *x.About
	}
	return ""
}

func (x *DelegateEntryV2) GetStatement() string {
	if x != nil && x.Statement != nil {
		return *x.Statement
	}
	return ""
}

func (x *DelegateEntryV2) GetVotesCount() int32 {
	if x != nil && x.VotesCount != nil {
		return *x.VotesCount
	}
	return 0
}

func (x *DelegateEntryV2) GetCreatedProposalsCount() int32 {
	if x != nil && x.CreatedProposalsCount != nil {
		return *x.CreatedProposalsCount
	}
	return 0
}

func (x *DelegateEntryV2) GetVotingPower() float64 {
	if x != nil && x.VotingPower != nil {
		return *x.VotingPower
	}
	return 0
}

func (x *DelegateEntryV2) GetTokenValue() *TokenValue {
	if x != nil {
		return x.TokenValue
	}
	return nil
}

func (x *DelegateEntryV2) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type DelegatesWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dao identified
	DaoId string `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	// Delegation type
	DelegationType DelegationType `protobuf:"varint,2,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	// Chain ID if provided (empty for split-delegation)
	ChainId *string `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	// List of delegates
	Delegates []*DelegateEntryV2 `protobuf:"bytes,4,rep,name=delegates,proto3" json:"delegates,omitempty"`
	// Total count of delegates
	TotalCnt      int32 `protobuf:"varint,5,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegatesWrapper) Reset() {
	*x = DelegatesWrapper{}
	mi := &file_storagepb_delegate_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegatesWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegatesWrapper) ProtoMessage() {}

func (x *DelegatesWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegatesWrapper.ProtoReflect.Descriptor instead.
func (*DelegatesWrapper) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{25}
}

func (x *DelegatesWrapper) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *DelegatesWrapper) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *DelegatesWrapper) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

func (x *DelegatesWrapper) GetDelegates() []*DelegateEntryV2 {
	if x != nil {
		return x.Delegates
	}
	return nil
}

func (x *DelegatesWrapper) GetTotalCnt() int32 {
	if x != nil {
		return x.TotalCnt
	}
	return 0
}

type GetDelegatesV2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of delegates grouped by specific delegation type and chain_id
	List []*DelegatesWrapper `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// Total count of delegates from all lists
	TotalCnt      int32 `protobuf:"varint,4,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatesV2Response) Reset() {
	*x = GetDelegatesV2Response{}
	mi := &file_storagepb_delegate_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatesV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatesV2Response) ProtoMessage() {}

func (x *GetDelegatesV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatesV2Response.ProtoReflect.Descriptor instead.
func (*GetDelegatesV2Response) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{26}
}

func (x *GetDelegatesV2Response) GetList() []*DelegatesWrapper {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetDelegatesV2Response) GetTotalCnt() int32 {
	if x != nil {
		return x.TotalCnt
	}
	return 0
}

type GetDelegatorsV2Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DaoId          string                 `protobuf:"bytes,1,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	QueryAccounts  []string               `protobuf:"bytes,2,rep,name=query_accounts,json=queryAccounts,proto3" json:"query_accounts,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	DelegationType DelegationType         `protobuf:"varint,5,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	ChainId        *string                `protobuf:"bytes,6,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDelegatorsV2Request) Reset() {
	*x = GetDelegatorsV2Request{}
	mi := &file_storagepb_delegate_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatorsV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatorsV2Request) ProtoMessage() {}

func (x *GetDelegatorsV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatorsV2Request.ProtoReflect.Descriptor instead.
func (*GetDelegatorsV2Request) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{27}
}

func (x *GetDelegatorsV2Request) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *GetDelegatorsV2Request) GetQueryAccounts() []string {
	if x != nil {
		return x.QueryAccounts
	}
	return nil
}

func (x *GetDelegatorsV2Request) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDelegatorsV2Request) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetDelegatorsV2Request) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *GetDelegatorsV2Request) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

type GetDelegatorsV2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of delegators
	List []*DelegatesWrapper `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// Total count of delegates from all lists
	TotalCnt      int32 `protobuf:"varint,2,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelegatorsV2Response) Reset() {
	*x = GetDelegatorsV2Response{}
	mi := &file_storagepb_delegate_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelegatorsV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelegatorsV2Response) ProtoMessage() {}

func (x *GetDelegatorsV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelegatorsV2Response.ProtoReflect.Descriptor instead.
func (*GetDelegatorsV2Response) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{28}
}

func (x *GetDelegatorsV2Response) GetList() []*DelegatesWrapper {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetDelegatorsV2Response) GetTotalCnt() int32 {
	if x != nil {
		return x.TotalCnt
	}
	return 0
}

type GetTopDelegatesV2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account address that initiates the delegation
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// specific dao_id for filtering
	DaoId *string `protobuf:"bytes,2,opt,name=dao_id,json=daoId,proto3,oneof" json:"dao_id,omitempty"`
	// Which delegation type used
	DelegationType DelegationType `protobuf:"varint,3,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	// In which chain
	ChainId       *string `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatesV2Request) Reset() {
	*x = GetTopDelegatesV2Request{}
	mi := &file_storagepb_delegate_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatesV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatesV2Request) ProtoMessage() {}

func (x *GetTopDelegatesV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatesV2Request.ProtoReflect.Descriptor instead.
func (*GetTopDelegatesV2Request) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{29}
}

func (x *GetTopDelegatesV2Request) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTopDelegatesV2Request) GetDaoId() string {
	if x != nil && x.DaoId != nil {
		return *x.DaoId
	}
	return ""
}

func (x *GetTopDelegatesV2Request) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *GetTopDelegatesV2Request) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

type GetTopDelegatesV2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total count of delegates from all lists
	TotalCnt int32 `protobuf:"varint,1,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	// List of delegates grouped by dao, delegation_type and chain_id and sorted by popularity index
	List          []*DelegatesWrapper `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatesV2Response) Reset() {
	*x = GetTopDelegatesV2Response{}
	mi := &file_storagepb_delegate_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatesV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatesV2Response) ProtoMessage() {}

func (x *GetTopDelegatesV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatesV2Response.ProtoReflect.Descriptor instead.
func (*GetTopDelegatesV2Response) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{30}
}

func (x *GetTopDelegatesV2Response) GetTotalCnt() int32 {
	if x != nil {
		return x.TotalCnt
	}
	return 0
}

func (x *GetTopDelegatesV2Response) GetList() []*DelegatesWrapper {
	if x != nil {
		return x.List
	}
	return nil
}

type GetTopDelegatorsV2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account address that initiates the delegation
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// specific dao_id for filtering
	DaoId *string `protobuf:"bytes,2,opt,name=dao_id,json=daoId,proto3,oneof" json:"dao_id,omitempty"`
	// Which delegation type used
	DelegationType DelegationType `protobuf:"varint,3,opt,name=delegation_type,json=delegationType,proto3,enum=storagepb.DelegationType" json:"delegation_type,omitempty"`
	// In which chain
	ChainId       *string `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3,oneof" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatorsV2Request) Reset() {
	*x = GetTopDelegatorsV2Request{}
	mi := &file_storagepb_delegate_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatorsV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatorsV2Request) ProtoMessage() {}

func (x *GetTopDelegatorsV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatorsV2Request.ProtoReflect.Descriptor instead.
func (*GetTopDelegatorsV2Request) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{31}
}

func (x *GetTopDelegatorsV2Request) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTopDelegatorsV2Request) GetDaoId() string {
	if x != nil && x.DaoId != nil {
		return *x.DaoId
	}
	return ""
}

func (x *GetTopDelegatorsV2Request) GetDelegationType() DelegationType {
	if x != nil {
		return x.DelegationType
	}
	return DelegationType_DELEGATION_TYPE_UNSPECIFIED
}

func (x *GetTopDelegatorsV2Request) GetChainId() string {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return ""
}

type GetTopDelegatorsV2Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total count of delegates from all lists
	TotalCnt int32 `protobuf:"varint,1,opt,name=total_cnt,json=totalCnt,proto3" json:"total_cnt,omitempty"`
	// List of delegates grouped by dao, delegation_type and chain_id and sorted by popularity index
	List          []*DelegatesWrapper `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDelegatorsV2Response) Reset() {
	*x = GetTopDelegatorsV2Response{}
	mi := &file_storagepb_delegate_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDelegatorsV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDelegatorsV2Response) ProtoMessage() {}

func (x *GetTopDelegatorsV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_delegate_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDelegatorsV2Response.ProtoReflect.Descriptor instead.
func (*GetTopDelegatorsV2Response) Descriptor() ([]byte, []int) {
	return file_storagepb_delegate_proto_rawDescGZIP(), []int{32}
}

func (x *GetTopDelegatorsV2Response) GetTotalCnt() int32 {
	if x != nil {
		return x.TotalCnt
	}
	return 0
}

func (x *GetTopDelegatorsV2Response) GetList() []*DelegatesWrapper {
	if x != nil {
		return x.List
	}
	return nil
}

var File_storagepb_delegate_proto protoreflect.FileDescriptor

const file_storagepb_delegate_proto_rawDesc = "" +
	"\n" +
	"\x18storagepb/delegate.proto\x12\tstoragepb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13storagepb/dao.proto\"\xad\x02\n" +
	"\x13GetDelegatesRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12%\n" +
	"\x0equery_accounts\x18\x02 \x03(\tR\rqueryAccounts\x12\x17\n" +
	"\x04sort\x18\x03 \x01(\tH\x00R\x04sort\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12G\n" +
	"\x0fdelegation_type\x18\x06 \x01(\x0e2\x19.storagepb.DelegationTypeH\x01R\x0edelegationType\x88\x01\x01\x12\x1e\n" +
	"\bchain_id\x18\a \x01(\tH\x02R\achainId\x88\x01\x01B\a\n" +
	"\x05_sortB\x12\n" +
	"\x10_delegation_typeB\v\n" +
	"\t_chain_id\"d\n" +
	"\x14GetDelegatesResponse\x126\n" +
	"\tdelegates\x18\x01 \x03(\v2\x18.storagepb.DelegateEntryR\tdelegates\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf9\x03\n" +
	"\rDelegateEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x19\n" +
	"\bens_name\x18\x02 \x01(\tR\aensName\x12'\n" +
	"\x0fdelegator_count\x18\x03 \x01(\x05R\x0edelegatorCount\x122\n" +
	"\x15percent_of_delegators\x18\x04 \x01(\x01R\x13percentOfDelegators\x12!\n" +
	"\fvoting_power\x18\x05 \x01(\x01R\vvotingPower\x125\n" +
	"\x17percent_of_voting_power\x18\x06 \x01(\x01R\x14percentOfVotingPower\x12\x14\n" +
	"\x05about\x18\a \x01(\tR\x05about\x12\x1c\n" +
	"\tstatement\x18\b \x01(\tR\tstatement\x12\x1f\n" +
	"\vvotes_count\x18\t \x01(\x05R\n" +
	"votesCount\x126\n" +
	"\x17created_proposals_count\x18\n" +
	" \x01(\x05R\x15createdProposalsCount\x12B\n" +
	"\x0fdelegation_type\x18\v \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationType\x12\x1e\n" +
	"\bchain_id\x18\f \x01(\tH\x00R\achainId\x88\x01\x01B\v\n" +
	"\t_chain_id\"f\n" +
	"\x0eDelegatorEntry\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x19\n" +
	"\bens_name\x18\x02 \x01(\tR\aensName\x12\x1f\n" +
	"\vtoken_value\x18\x05 \x01(\tR\n" +
	"tokenValue\"\xbd\x01\n" +
	"\x19GetDelegateProfileRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12B\n" +
	"\x0fdelegation_type\x18\x03 \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationType\x12\x1e\n" +
	"\bchain_id\x18\x04 \x01(\tH\x00R\achainId\x88\x01\x01B\v\n" +
	"\t_chain_id\"\x8c\x03\n" +
	"\x1aGetDelegateProfileResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12!\n" +
	"\fvoting_power\x18\x02 \x01(\x01R\vvotingPower\x12%\n" +
	"\x0eincoming_power\x18\x03 \x01(\x01R\rincomingPower\x12%\n" +
	"\x0eoutgoing_power\x18\x04 \x01(\x01R\routgoingPower\x125\n" +
	"\x17percent_of_voting_power\x18\x05 \x01(\x01R\x14percentOfVotingPower\x122\n" +
	"\x15percent_of_delegators\x18\x06 \x01(\x01R\x13percentOfDelegators\x12<\n" +
	"\tdelegates\x18\a \x03(\v2\x1e.storagepb.ProfileDelegateItemR\tdelegates\x12:\n" +
	"\n" +
	"expiration\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"\x8b\x01\n" +
	"\x13ProfileDelegateItem\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x19\n" +
	"\bens_name\x18\x02 \x01(\tR\aensName\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12'\n" +
	"\x0fdelegated_power\x18\x04 \x01(\x01R\x0edelegatedPower\"2\n" +
	"\x16GetTopDelegatesRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xb8\x01\n" +
	"\x11DelegationDetails\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x19\n" +
	"\bens_name\x18\x02 \x01(\tR\aensName\x122\n" +
	"\x15percent_of_delegators\x18\x03 \x01(\x05R\x13percentOfDelegators\x12:\n" +
	"\n" +
	"expiration\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\"\x8b\x01\n" +
	"\x10DelegatesSummary\x12$\n" +
	"\x03dao\x18\x01 \x01(\v2\x12.storagepb.DaoInfoR\x03dao\x120\n" +
	"\x04list\x18\x02 \x03(\v2\x1c.storagepb.DelegationDetailsR\x04list\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"~\n" +
	"\x17GetTopDelegatesResponse\x122\n" +
	"\x15total_delegates_count\x18\x01 \x01(\x05R\x13totalDelegatesCount\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.storagepb.DelegatesSummaryR\x04list\"3\n" +
	"\x17GetTopDelegatorsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x8b\x01\n" +
	"\x10DelegatorSummary\x12$\n" +
	"\x03dao\x18\x01 \x01(\v2\x12.storagepb.DaoInfoR\x03dao\x120\n" +
	"\x04list\x18\x02 \x03(\v2\x1c.storagepb.DelegationDetailsR\x04list\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x81\x01\n" +
	"\x18GetTopDelegatorsResponse\x124\n" +
	"\x16total_delegators_count\x18\x01 \x01(\x05R\x14totalDelegatorsCount\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.storagepb.DelegatorSummaryR\x04list\"7\n" +
	"\x1bGetDelegationSummaryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x88\x01\n" +
	"\x1cGetDelegationSummaryResponse\x124\n" +
	"\x16total_delegators_count\x18\x01 \x01(\x05R\x14totalDelegatorsCount\x122\n" +
	"\x15total_delegates_count\x18\x02 \x01(\x05R\x13totalDelegatesCount\"\x89\x01\n" +
	"\x18GetDelegatesByDaoRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\rH\x00R\x06offset\x88\x01\x01B\t\n" +
	"\a_offset\"n\n" +
	"\x19GetDelegatesByDaoResponse\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.storagepb.DelegationDetailsR\x04list\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x8a\x01\n" +
	"\x19GetDelegatorsByDaoRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\rH\x00R\x06offset\x88\x01\x01B\t\n" +
	"\a_offset\"o\n" +
	"\x1aGetDelegatorsByDaoResponse\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.storagepb.DelegationDetailsR\x04list\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xe4\x01\n" +
	"\x14GetDelegatorsRequest\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x1b\n" +
	"\x06offset\x18\x05 \x01(\rH\x00R\x06offset\x88\x01\x01\x12B\n" +
	"\x0fdelegation_type\x18\x06 \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationTypeB\t\n" +
	"\a_offset\"g\n" +
	"\x15GetDelegatorsResponse\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.storagepb.DelegatorEntryR\x04list\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x96\x02\n" +
	"\x15GetDelegatesV2Request\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12%\n" +
	"\x0equery_accounts\x18\x02 \x03(\tR\rqueryAccounts\x12\x17\n" +
	"\x04sort\x18\x03 \x01(\tH\x00R\x04sort\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12B\n" +
	"\x0fdelegation_type\x18\x06 \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationType\x12\x1e\n" +
	"\bchain_id\x18\a \x01(\tH\x01R\achainId\x88\x01\x01B\a\n" +
	"\x05_sortB\v\n" +
	"\t_chain_id\"V\n" +
	"\n" +
	"TokenValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\x05R\bdecimals\"\xee\x05\n" +
	"\x0fDelegateEntryV2\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x19\n" +
	"\bens_name\x18\x02 \x01(\tR\aensName\x12,\n" +
	"\x0fdelegator_count\x18\x03 \x01(\x05H\x00R\x0edelegatorCount\x88\x01\x01\x127\n" +
	"\x15percent_of_delegators\x18\x04 \x01(\x01H\x01R\x13percentOfDelegators\x88\x01\x01\x12:\n" +
	"\x17percent_of_voting_power\x18\x05 \x01(\x01H\x02R\x14percentOfVotingPower\x88\x01\x01\x12\x19\n" +
	"\x05about\x18\x06 \x01(\tH\x03R\x05about\x88\x01\x01\x12!\n" +
	"\tstatement\x18\a \x01(\tH\x04R\tstatement\x88\x01\x01\x12$\n" +
	"\vvotes_count\x18\b \x01(\x05H\x05R\n" +
	"votesCount\x88\x01\x01\x12;\n" +
	"\x17created_proposals_count\x18\t \x01(\x05H\x06R\x15createdProposalsCount\x88\x01\x01\x12&\n" +
	"\fvoting_power\x18\n" +
	" \x01(\x01H\aR\vvotingPower\x88\x01\x01\x12;\n" +
	"\vtoken_value\x18\v \x01(\v2\x15.storagepb.TokenValueH\bR\n" +
	"tokenValue\x88\x01\x01\x12?\n" +
	"\n" +
	"expiration\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\tR\n" +
	"expiration\x88\x01\x01B\x12\n" +
	"\x10_delegator_countB\x18\n" +
	"\x16_percent_of_delegatorsB\x1a\n" +
	"\x18_percent_of_voting_powerB\b\n" +
	"\x06_aboutB\f\n" +
	"\n" +
	"_statementB\x0e\n" +
	"\f_votes_countB\x1a\n" +
	"\x18_created_proposals_countB\x0f\n" +
	"\r_voting_powerB\x0e\n" +
	"\f_token_valueB\r\n" +
	"\v_expiration\"\xf1\x01\n" +
	"\x10DelegatesWrapper\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12B\n" +
	"\x0fdelegation_type\x18\x02 \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationType\x12\x1e\n" +
	"\bchain_id\x18\x03 \x01(\tH\x00R\achainId\x88\x01\x01\x128\n" +
	"\tdelegates\x18\x04 \x03(\v2\x1a.storagepb.DelegateEntryV2R\tdelegates\x12\x1b\n" +
	"\ttotal_cnt\x18\x05 \x01(\x05R\btotalCntB\v\n" +
	"\t_chain_id\"f\n" +
	"\x16GetDelegatesV2Response\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.storagepb.DelegatesWrapperR\x04list\x12\x1b\n" +
	"\ttotal_cnt\x18\x04 \x01(\x05R\btotalCnt\"\xf5\x01\n" +
	"\x16GetDelegatorsV2Request\x12\x15\n" +
	"\x06dao_id\x18\x01 \x01(\tR\x05daoId\x12%\n" +
	"\x0equery_accounts\x18\x02 \x03(\tR\rqueryAccounts\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12B\n" +
	"\x0fdelegation_type\x18\x05 \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationType\x12\x1e\n" +
	"\bchain_id\x18\x06 \x01(\tH\x00R\achainId\x88\x01\x01B\v\n" +
	"\t_chain_id\"g\n" +
	"\x17GetDelegatorsV2Response\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.storagepb.DelegatesWrapperR\x04list\x12\x1b\n" +
	"\ttotal_cnt\x18\x02 \x01(\x05R\btotalCnt\"\xcc\x01\n" +
	"\x18GetTopDelegatesV2Request\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\x06dao_id\x18\x02 \x01(\tH\x00R\x05daoId\x88\x01\x01\x12B\n" +
	"\x0fdelegation_type\x18\x03 \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationType\x12\x1e\n" +
	"\bchain_id\x18\x04 \x01(\tH\x01R\achainId\x88\x01\x01B\t\n" +
	"\a_dao_idB\v\n" +
	"\t_chain_id\"i\n" +
	"\x19GetTopDelegatesV2Response\x12\x1b\n" +
	"\ttotal_cnt\x18\x01 \x01(\x05R\btotalCnt\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.storagepb.DelegatesWrapperR\x04list\"\xcd\x01\n" +
	"\x19GetTopDelegatorsV2Request\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\x06dao_id\x18\x02 \x01(\tH\x00R\x05daoId\x88\x01\x01\x12B\n" +
	"\x0fdelegation_type\x18\x03 \x01(\x0e2\x19.storagepb.DelegationTypeR\x0edelegationType\x12\x1e\n" +
	"\bchain_id\x18\x04 \x01(\tH\x01R\achainId\x88\x01\x01B\t\n" +
	"\a_dao_idB\v\n" +
	"\t_chain_id\"j\n" +
	"\x1aGetTopDelegatorsV2Response\x12\x1b\n" +
	"\ttotal_cnt\x18\x01 \x01(\x05R\btotalCnt\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.storagepb.DelegatesWrapperR\x04list*\xba\x01\n" +
	"\x0eDelegationType\x12\x1f\n" +
	"\x1bDELEGATION_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" DELEGATION_TYPE_SPLIT_DELEGATION\x10\x01\x12\x1e\n" +
	"\x1aDELEGATION_TYPE_DELEGATION\x10\x02\x12\x1f\n" +
	"\x1bDELEGATION_TYPE_ERC20_VOTES\x10\x03\x12 \n" +
	"\x1cDELEGATION_TYPE_UNRECOGNIZED\x10\x042\xe9\b\n" +
	"\bDelegate\x12O\n" +
	"\fGetDelegates\x12\x1e.storagepb.GetDelegatesRequest\x1a\x1f.storagepb.GetDelegatesResponse\x12R\n" +
	"\rGetDelegators\x12\x1f.storagepb.GetDelegatorsRequest\x1a .storagepb.GetDelegatorsResponse\x12a\n" +
	"\x12GetDelegateProfile\x12$.storagepb.GetDelegateProfileRequest\x1a%.storagepb.GetDelegateProfileResponse\x12X\n" +
	"\x0fGetTopDelegates\x12!.storagepb.GetTopDelegatesRequest\x1a\".storagepb.GetTopDelegatesResponse\x12[\n" +
	"\x10GetTopDelegators\x12\".storagepb.GetTopDelegatorsRequest\x1a#.storagepb.GetTopDelegatorsResponse\x12g\n" +
	"\x14GetDelegationSummary\x12&.storagepb.GetDelegationSummaryRequest\x1a'.storagepb.GetDelegationSummaryResponse\x12^\n" +
	"\x11GetDelegatesByDao\x12#.storagepb.GetDelegatesByDaoRequest\x1a$.storagepb.GetDelegatesByDaoResponse\x12a\n" +
	"\x12GetDelegatorsByDao\x12$.storagepb.GetDelegatorsByDaoRequest\x1a%.storagepb.GetDelegatorsByDaoResponse\x12U\n" +
	"\x0eGetDelegatesV2\x12 .storagepb.GetDelegatesV2Request\x1a!.storagepb.GetDelegatesV2Response\x12X\n" +
	"\x0fGetDelegatorsV2\x12!.storagepb.GetDelegatorsV2Request\x1a\".storagepb.GetDelegatorsV2Response\x12^\n" +
	"\x11GetTopDelegatesV2\x12#.storagepb.GetTopDelegatesV2Request\x1a$.storagepb.GetTopDelegatesV2Response\x12a\n" +
	"\x12GetTopDelegatorsV2\x12$.storagepb.GetTopDelegatorsV2Request\x1a%.storagepb.GetTopDelegatorsV2ResponseB\rZ\v.;storagepbb\x06proto3"

var (
	file_storagepb_delegate_proto_rawDescOnce sync.Once
	file_storagepb_delegate_proto_rawDescData []byte
)

func file_storagepb_delegate_proto_rawDescGZIP() []byte {
	file_storagepb_delegate_proto_rawDescOnce.Do(func() {
		file_storagepb_delegate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storagepb_delegate_proto_rawDesc), len(file_storagepb_delegate_proto_rawDesc)))
	})
	return file_storagepb_delegate_proto_rawDescData
}

var file_storagepb_delegate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storagepb_delegate_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_storagepb_delegate_proto_goTypes = []any{
	(DelegationType)(0),                  // 0: storagepb.DelegationType
	(*GetDelegatesRequest)(nil),          // 1: storagepb.GetDelegatesRequest
	(*GetDelegatesResponse)(nil),         // 2: storagepb.GetDelegatesResponse
	(*DelegateEntry)(nil),                // 3: storagepb.DelegateEntry
	(*DelegatorEntry)(nil),               // 4: storagepb.DelegatorEntry
	(*GetDelegateProfileRequest)(nil),    // 5: storagepb.GetDelegateProfileRequest
	(*GetDelegateProfileResponse)(nil),   // 6: storagepb.GetDelegateProfileResponse
	(*ProfileDelegateItem)(nil),          // 7: storagepb.ProfileDelegateItem
	(*GetTopDelegatesRequest)(nil),       // 8: storagepb.GetTopDelegatesRequest
	(*DelegationDetails)(nil),            // 9: storagepb.DelegationDetails
	(*DelegatesSummary)(nil),             // 10: storagepb.DelegatesSummary
	(*GetTopDelegatesResponse)(nil),      // 11: storagepb.GetTopDelegatesResponse
	(*GetTopDelegatorsRequest)(nil),      // 12: storagepb.GetTopDelegatorsRequest
	(*DelegatorSummary)(nil),             // 13: storagepb.DelegatorSummary
	(*GetTopDelegatorsResponse)(nil),     // 14: storagepb.GetTopDelegatorsResponse
	(*GetDelegationSummaryRequest)(nil),  // 15: storagepb.GetDelegationSummaryRequest
	(*GetDelegationSummaryResponse)(nil), // 16: storagepb.GetDelegationSummaryResponse
	(*GetDelegatesByDaoRequest)(nil),     // 17: storagepb.GetDelegatesByDaoRequest
	(*GetDelegatesByDaoResponse)(nil),    // 18: storagepb.GetDelegatesByDaoResponse
	(*GetDelegatorsByDaoRequest)(nil),    // 19: storagepb.GetDelegatorsByDaoRequest
	(*GetDelegatorsByDaoResponse)(nil),   // 20: storagepb.GetDelegatorsByDaoResponse
	(*GetDelegatorsRequest)(nil),         // 21: storagepb.GetDelegatorsRequest
	(*GetDelegatorsResponse)(nil),        // 22: storagepb.GetDelegatorsResponse
	(*GetDelegatesV2Request)(nil),        // 23: storagepb.GetDelegatesV2Request
	(*TokenValue)(nil),                   // 24: storagepb.TokenValue
	(*DelegateEntryV2)(nil),              // 25: storagepb.DelegateEntryV2
	(*DelegatesWrapper)(nil),             // 26: storagepb.DelegatesWrapper
	(*GetDelegatesV2Response)(nil),       // 27: storagepb.GetDelegatesV2Response
	(*GetDelegatorsV2Request)(nil),       // 28: storagepb.GetDelegatorsV2Request
	(*GetDelegatorsV2Response)(nil),      // 29: storagepb.GetDelegatorsV2Response
	(*GetTopDelegatesV2Request)(nil),     // 30: storagepb.GetTopDelegatesV2Request
	(*GetTopDelegatesV2Response)(nil),    // 31: storagepb.GetTopDelegatesV2Response
	(*GetTopDelegatorsV2Request)(nil),    // 32: storagepb.GetTopDelegatorsV2Request
	(*GetTopDelegatorsV2Response)(nil),   // 33: storagepb.GetTopDelegatorsV2Response
	(*timestamppb.Timestamp)(nil),        // 34: google.protobuf.Timestamp
	(*DaoInfo)(nil),                      // 35: storagepb.DaoInfo
}
var file_storagepb_delegate_proto_depIdxs = []int32{
	0,  // 0: storagepb.GetDelegatesRequest.delegation_type:type_name -> storagepb.DelegationType
	3,  // 1: storagepb.GetDelegatesResponse.delegates:type_name -> storagepb.DelegateEntry
	0,  // 2: storagepb.DelegateEntry.delegation_type:type_name -> storagepb.DelegationType
	0,  // 3: storagepb.GetDelegateProfileRequest.delegation_type:type_name -> storagepb.DelegationType
	7,  // 4: storagepb.GetDelegateProfileResponse.delegates:type_name -> storagepb.ProfileDelegateItem
	34, // 5: storagepb.GetDelegateProfileResponse.expiration:type_name -> google.protobuf.Timestamp
	34, // 6: storagepb.DelegationDetails.expiration:type_name -> google.protobuf.Timestamp
	35, // 7: storagepb.DelegatesSummary.dao:type_name -> storagepb.DaoInfo
	9,  // 8: storagepb.DelegatesSummary.list:type_name -> storagepb.DelegationDetails
	10, // 9: storagepb.GetTopDelegatesResponse.list:type_name -> storagepb.DelegatesSummary
	35, // 10: storagepb.DelegatorSummary.dao:type_name -> storagepb.DaoInfo
	9,  // 11: storagepb.DelegatorSummary.list:type_name -> storagepb.DelegationDetails
	13, // 12: storagepb.GetTopDelegatorsResponse.list:type_name -> storagepb.DelegatorSummary
	9,  // 13: storagepb.GetDelegatesByDaoResponse.list:type_name -> storagepb.DelegationDetails
	9,  // 14: storagepb.GetDelegatorsByDaoResponse.list:type_name -> storagepb.DelegationDetails
	0,  // 15: storagepb.GetDelegatorsRequest.delegation_type:type_name -> storagepb.DelegationType
	4,  // 16: storagepb.GetDelegatorsResponse.list:type_name -> storagepb.DelegatorEntry
	0,  // 17: storagepb.GetDelegatesV2Request.delegation_type:type_name -> storagepb.DelegationType
	24, // 18: storagepb.DelegateEntryV2.token_value:type_name -> storagepb.TokenValue
	34, // 19: storagepb.DelegateEntryV2.expiration:type_name -> google.protobuf.Timestamp
	0,  // 20: storagepb.DelegatesWrapper.delegation_type:type_name -> storagepb.DelegationType
	25, // 21: storagepb.DelegatesWrapper.delegates:type_name -> storagepb.DelegateEntryV2
	26, // 22: storagepb.GetDelegatesV2Response.list:type_name -> storagepb.DelegatesWrapper
	0,  // 23: storagepb.GetDelegatorsV2Request.delegation_type:type_name -> storagepb.DelegationType
	26, // 24: storagepb.GetDelegatorsV2Response.list:type_name -> storagepb.DelegatesWrapper
	0,  // 25: storagepb.GetTopDelegatesV2Request.delegation_type:type_name -> storagepb.DelegationType
	26, // 26: storagepb.GetTopDelegatesV2Response.list:type_name -> storagepb.DelegatesWrapper
	0,  // 27: storagepb.GetTopDelegatorsV2Request.delegation_type:type_name -> storagepb.DelegationType
	26, // 28: storagepb.GetTopDelegatorsV2Response.list:type_name -> storagepb.DelegatesWrapper
	1,  // 29: storagepb.Delegate.GetDelegates:input_type -> storagepb.GetDelegatesRequest
	21, // 30: storagepb.Delegate.GetDelegators:input_type -> storagepb.GetDelegatorsRequest
	5,  // 31: storagepb.Delegate.GetDelegateProfile:input_type -> storagepb.GetDelegateProfileRequest
	8,  // 32: storagepb.Delegate.GetTopDelegates:input_type -> storagepb.GetTopDelegatesRequest
	12, // 33: storagepb.Delegate.GetTopDelegators:input_type -> storagepb.GetTopDelegatorsRequest
	15, // 34: storagepb.Delegate.GetDelegationSummary:input_type -> storagepb.GetDelegationSummaryRequest
	17, // 35: storagepb.Delegate.GetDelegatesByDao:input_type -> storagepb.GetDelegatesByDaoRequest
	19, // 36: storagepb.Delegate.GetDelegatorsByDao:input_type -> storagepb.GetDelegatorsByDaoRequest
	23, // 37: storagepb.Delegate.GetDelegatesV2:input_type -> storagepb.GetDelegatesV2Request
	28, // 38: storagepb.Delegate.GetDelegatorsV2:input_type -> storagepb.GetDelegatorsV2Request
	30, // 39: storagepb.Delegate.GetTopDelegatesV2:input_type -> storagepb.GetTopDelegatesV2Request
	32, // 40: storagepb.Delegate.GetTopDelegatorsV2:input_type -> storagepb.GetTopDelegatorsV2Request
	2,  // 41: storagepb.Delegate.GetDelegates:output_type -> storagepb.GetDelegatesResponse
	22, // 42: storagepb.Delegate.GetDelegators:output_type -> storagepb.GetDelegatorsResponse
	6,  // 43: storagepb.Delegate.GetDelegateProfile:output_type -> storagepb.GetDelegateProfileResponse
	11, // 44: storagepb.Delegate.GetTopDelegates:output_type -> storagepb.GetTopDelegatesResponse
	14, // 45: storagepb.Delegate.GetTopDelegators:output_type -> storagepb.GetTopDelegatorsResponse
	16, // 46: storagepb.Delegate.GetDelegationSummary:output_type -> storagepb.GetDelegationSummaryResponse
	18, // 47: storagepb.Delegate.GetDelegatesByDao:output_type -> storagepb.GetDelegatesByDaoResponse
	20, // 48: storagepb.Delegate.GetDelegatorsByDao:output_type -> storagepb.GetDelegatorsByDaoResponse
	27, // 49: storagepb.Delegate.GetDelegatesV2:output_type -> storagepb.GetDelegatesV2Response
	29, // 50: storagepb.Delegate.GetDelegatorsV2:output_type -> storagepb.GetDelegatorsV2Response
	31, // 51: storagepb.Delegate.GetTopDelegatesV2:output_type -> storagepb.GetTopDelegatesV2Response
	33, // 52: storagepb.Delegate.GetTopDelegatorsV2:output_type -> storagepb.GetTopDelegatorsV2Response
	41, // [41:53] is the sub-list for method output_type
	29, // [29:41] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_storagepb_delegate_proto_init() }
func file_storagepb_delegate_proto_init() {
	if File_storagepb_delegate_proto != nil {
		return
	}
	file_storagepb_dao_proto_init()
	file_storagepb_delegate_proto_msgTypes[0].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[2].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[4].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[16].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[18].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[20].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[22].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[24].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[25].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[27].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[29].OneofWrappers = []any{}
	file_storagepb_delegate_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storagepb_delegate_proto_rawDesc), len(file_storagepb_delegate_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storagepb_delegate_proto_goTypes,
		DependencyIndexes: file_storagepb_delegate_proto_depIdxs,
		EnumInfos:         file_storagepb_delegate_proto_enumTypes,
		MessageInfos:      file_storagepb_delegate_proto_msgTypes,
	}.Build()
	File_storagepb_delegate_proto = out.File
	file_storagepb_delegate_proto_goTypes = nil
	file_storagepb_delegate_proto_depIdxs = nil
}
