// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: storagepb/delegate.proto

package storagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Delegate_GetDelegates_FullMethodName         = "/storagepb.Delegate/GetDelegates"
	Delegate_GetDelegateProfile_FullMethodName   = "/storagepb.Delegate/GetDelegateProfile"
	Delegate_GetTopDelegates_FullMethodName      = "/storagepb.Delegate/GetTopDelegates"
	Delegate_GetTopDelegators_FullMethodName     = "/storagepb.Delegate/GetTopDelegators"
	Delegate_GetDelegationSummary_FullMethodName = "/storagepb.Delegate/GetDelegationSummary"
	Delegate_GetDelegatesByDao_FullMethodName    = "/storagepb.Delegate/GetDelegatesByDao"
	Delegate_GetDelegatorsByDao_FullMethodName   = "/storagepb.Delegate/GetDelegatorsByDao"
)

// DelegateClient is the client API for Delegate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DelegateClient interface {
	// GetDelegates returns list of delegates get from Snapshot
	GetDelegates(ctx context.Context, in *GetDelegatesRequest, opts ...grpc.CallOption) (*GetDelegatesResponse, error)
	GetDelegateProfile(ctx context.Context, in *GetDelegateProfileRequest, opts ...grpc.CallOption) (*GetDelegateProfileResponse, error)
	// GetTopDelegates returns list of first 5 addresses of delegations based on internal data grouped by dao
	GetTopDelegates(ctx context.Context, in *GetTopDelegatesRequest, opts ...grpc.CallOption) (*GetTopDelegatesResponse, error)
	// GetTopDelegators returns list of first 5 addresses of delegators based on internal data grouped by dao
	GetTopDelegators(ctx context.Context, in *GetTopDelegatorsRequest, opts ...grpc.CallOption) (*GetTopDelegatorsResponse, error)
	// GetDelegatesSummary returns count of delegators and delegations
	GetDelegationSummary(ctx context.Context, in *GetDelegationSummaryRequest, opts ...grpc.CallOption) (*GetDelegationSummaryResponse, error)
	// GetDelegatesByDao returns list of delegations based on internal data filtered by params
	GetDelegatesByDao(ctx context.Context, in *GetDelegatesByDaoRequest, opts ...grpc.CallOption) (*GetDelegatesByDaoResponse, error)
	// GetDelegatorsByDao returns list of delegations based on internal data filtered by params
	GetDelegatorsByDao(ctx context.Context, in *GetDelegatorsByDaoRequest, opts ...grpc.CallOption) (*GetDelegatorsByDaoResponse, error)
}

type delegateClient struct {
	cc grpc.ClientConnInterface
}

func NewDelegateClient(cc grpc.ClientConnInterface) DelegateClient {
	return &delegateClient{cc}
}

func (c *delegateClient) GetDelegates(ctx context.Context, in *GetDelegatesRequest, opts ...grpc.CallOption) (*GetDelegatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegatesResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetDelegateProfile(ctx context.Context, in *GetDelegateProfileRequest, opts ...grpc.CallOption) (*GetDelegateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegateProfileResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetTopDelegates(ctx context.Context, in *GetTopDelegatesRequest, opts ...grpc.CallOption) (*GetTopDelegatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopDelegatesResponse)
	err := c.cc.Invoke(ctx, Delegate_GetTopDelegates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetTopDelegators(ctx context.Context, in *GetTopDelegatorsRequest, opts ...grpc.CallOption) (*GetTopDelegatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopDelegatorsResponse)
	err := c.cc.Invoke(ctx, Delegate_GetTopDelegators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetDelegationSummary(ctx context.Context, in *GetDelegationSummaryRequest, opts ...grpc.CallOption) (*GetDelegationSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegationSummaryResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegationSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetDelegatesByDao(ctx context.Context, in *GetDelegatesByDaoRequest, opts ...grpc.CallOption) (*GetDelegatesByDaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegatesByDaoResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegatesByDao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delegateClient) GetDelegatorsByDao(ctx context.Context, in *GetDelegatorsByDaoRequest, opts ...grpc.CallOption) (*GetDelegatorsByDaoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelegatorsByDaoResponse)
	err := c.cc.Invoke(ctx, Delegate_GetDelegatorsByDao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelegateServer is the server API for Delegate service.
// All implementations must embed UnimplementedDelegateServer
// for forward compatibility.
type DelegateServer interface {
	// GetDelegates returns list of delegates get from Snapshot
	GetDelegates(context.Context, *GetDelegatesRequest) (*GetDelegatesResponse, error)
	GetDelegateProfile(context.Context, *GetDelegateProfileRequest) (*GetDelegateProfileResponse, error)
	// GetTopDelegates returns list of first 5 addresses of delegations based on internal data grouped by dao
	GetTopDelegates(context.Context, *GetTopDelegatesRequest) (*GetTopDelegatesResponse, error)
	// GetTopDelegators returns list of first 5 addresses of delegators based on internal data grouped by dao
	GetTopDelegators(context.Context, *GetTopDelegatorsRequest) (*GetTopDelegatorsResponse, error)
	// GetDelegatesSummary returns count of delegators and delegations
	GetDelegationSummary(context.Context, *GetDelegationSummaryRequest) (*GetDelegationSummaryResponse, error)
	// GetDelegatesByDao returns list of delegations based on internal data filtered by params
	GetDelegatesByDao(context.Context, *GetDelegatesByDaoRequest) (*GetDelegatesByDaoResponse, error)
	// GetDelegatorsByDao returns list of delegations based on internal data filtered by params
	GetDelegatorsByDao(context.Context, *GetDelegatorsByDaoRequest) (*GetDelegatorsByDaoResponse, error)
	mustEmbedUnimplementedDelegateServer()
}

// UnimplementedDelegateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDelegateServer struct{}

func (UnimplementedDelegateServer) GetDelegates(context.Context, *GetDelegatesRequest) (*GetDelegatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegates not implemented")
}
func (UnimplementedDelegateServer) GetDelegateProfile(context.Context, *GetDelegateProfileRequest) (*GetDelegateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegateProfile not implemented")
}
func (UnimplementedDelegateServer) GetTopDelegates(context.Context, *GetTopDelegatesRequest) (*GetTopDelegatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopDelegates not implemented")
}
func (UnimplementedDelegateServer) GetTopDelegators(context.Context, *GetTopDelegatorsRequest) (*GetTopDelegatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopDelegators not implemented")
}
func (UnimplementedDelegateServer) GetDelegationSummary(context.Context, *GetDelegationSummaryRequest) (*GetDelegationSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegationSummary not implemented")
}
func (UnimplementedDelegateServer) GetDelegatesByDao(context.Context, *GetDelegatesByDaoRequest) (*GetDelegatesByDaoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegatesByDao not implemented")
}
func (UnimplementedDelegateServer) GetDelegatorsByDao(context.Context, *GetDelegatorsByDaoRequest) (*GetDelegatorsByDaoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegatorsByDao not implemented")
}
func (UnimplementedDelegateServer) mustEmbedUnimplementedDelegateServer() {}
func (UnimplementedDelegateServer) testEmbeddedByValue()                  {}

// UnsafeDelegateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DelegateServer will
// result in compilation errors.
type UnsafeDelegateServer interface {
	mustEmbedUnimplementedDelegateServer()
}

func RegisterDelegateServer(s grpc.ServiceRegistrar, srv DelegateServer) {
	// If the following call pancis, it indicates UnimplementedDelegateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Delegate_ServiceDesc, srv)
}

func _Delegate_GetDelegates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegates(ctx, req.(*GetDelegatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetDelegateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegateProfile(ctx, req.(*GetDelegateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetTopDelegates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopDelegatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetTopDelegates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetTopDelegates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetTopDelegates(ctx, req.(*GetTopDelegatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetTopDelegators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopDelegatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetTopDelegators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetTopDelegators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetTopDelegators(ctx, req.(*GetTopDelegatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetDelegationSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegationSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegationSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegationSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegationSummary(ctx, req.(*GetDelegationSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetDelegatesByDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegatesByDaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegatesByDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegatesByDao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegatesByDao(ctx, req.(*GetDelegatesByDaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Delegate_GetDelegatorsByDao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelegatorsByDaoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegateServer).GetDelegatorsByDao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delegate_GetDelegatorsByDao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegateServer).GetDelegatorsByDao(ctx, req.(*GetDelegatorsByDaoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Delegate_ServiceDesc is the grpc.ServiceDesc for Delegate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Delegate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storagepb.Delegate",
	HandlerType: (*DelegateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDelegates",
			Handler:    _Delegate_GetDelegates_Handler,
		},
		{
			MethodName: "GetDelegateProfile",
			Handler:    _Delegate_GetDelegateProfile_Handler,
		},
		{
			MethodName: "GetTopDelegates",
			Handler:    _Delegate_GetTopDelegates_Handler,
		},
		{
			MethodName: "GetTopDelegators",
			Handler:    _Delegate_GetTopDelegators_Handler,
		},
		{
			MethodName: "GetDelegationSummary",
			Handler:    _Delegate_GetDelegationSummary_Handler,
		},
		{
			MethodName: "GetDelegatesByDao",
			Handler:    _Delegate_GetDelegatesByDao_Handler,
		},
		{
			MethodName: "GetDelegatorsByDao",
			Handler:    _Delegate_GetDelegatorsByDao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storagepb/delegate.proto",
}
