// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: storagepb/stats.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTotalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalsRequest) Reset() {
	*x = GetTotalsRequest{}
	mi := &file_storagepb_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalsRequest) ProtoMessage() {}

func (x *GetTotalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalsRequest.ProtoReflect.Descriptor instead.
func (*GetTotalsRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_stats_proto_rawDescGZIP(), []int{0}
}

type DaoStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	TotalVerified int64                  `protobuf:"varint,2,opt,name=total_verified,json=totalVerified,proto3" json:"total_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaoStats) Reset() {
	*x = DaoStats{}
	mi := &file_storagepb_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaoStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaoStats) ProtoMessage() {}

func (x *DaoStats) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaoStats.ProtoReflect.Descriptor instead.
func (*DaoStats) Descriptor() ([]byte, []int) {
	return file_storagepb_stats_proto_rawDescGZIP(), []int{1}
}

func (x *DaoStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DaoStats) GetTotalVerified() int64 {
	if x != nil {
		return x.TotalVerified
	}
	return 0
}

type ProposalsStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalsStats) Reset() {
	*x = ProposalsStats{}
	mi := &file_storagepb_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalsStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalsStats) ProtoMessage() {}

func (x *ProposalsStats) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalsStats.ProtoReflect.Descriptor instead.
func (*ProposalsStats) Descriptor() ([]byte, []int) {
	return file_storagepb_stats_proto_rawDescGZIP(), []int{2}
}

func (x *ProposalsStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTotalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dao           *DaoStats              `protobuf:"bytes,1,opt,name=dao,proto3" json:"dao,omitempty"`
	Proposals     *ProposalsStats        `protobuf:"bytes,2,opt,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalsResponse) Reset() {
	*x = GetTotalsResponse{}
	mi := &file_storagepb_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalsResponse) ProtoMessage() {}

func (x *GetTotalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalsResponse.ProtoReflect.Descriptor instead.
func (*GetTotalsResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetTotalsResponse) GetDao() *DaoStats {
	if x != nil {
		return x.Dao
	}
	return nil
}

func (x *GetTotalsResponse) GetProposals() *ProposalsStats {
	if x != nil {
		return x.Proposals
	}
	return nil
}

var File_storagepb_stats_proto protoreflect.FileDescriptor

const file_storagepb_stats_proto_rawDesc = "" +
	"\n" +
	"\x15storagepb/stats.proto\x12\tstoragepb\"\x12\n" +
	"\x10GetTotalsRequest\"G\n" +
	"\bDaoStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12%\n" +
	"\x0etotal_verified\x18\x02 \x01(\x03R\rtotalVerified\"&\n" +
	"\x0eProposalsStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\"s\n" +
	"\x11GetTotalsResponse\x12%\n" +
	"\x03dao\x18\x01 \x01(\v2\x13.storagepb.DaoStatsR\x03dao\x127\n" +
	"\tproposals\x18\x02 \x01(\v2\x19.storagepb.ProposalsStatsR\tproposals2O\n" +
	"\x05Stats\x12F\n" +
	"\tGetTotals\x12\x1b.storagepb.GetTotalsRequest\x1a\x1c.storagepb.GetTotalsResponseB\rZ\v.;storagepbb\x06proto3"

var (
	file_storagepb_stats_proto_rawDescOnce sync.Once
	file_storagepb_stats_proto_rawDescData []byte
)

func file_storagepb_stats_proto_rawDescGZIP() []byte {
	file_storagepb_stats_proto_rawDescOnce.Do(func() {
		file_storagepb_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storagepb_stats_proto_rawDesc), len(file_storagepb_stats_proto_rawDesc)))
	})
	return file_storagepb_stats_proto_rawDescData
}

var file_storagepb_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storagepb_stats_proto_goTypes = []any{
	(*GetTotalsRequest)(nil),  // 0: storagepb.GetTotalsRequest
	(*DaoStats)(nil),          // 1: storagepb.DaoStats
	(*ProposalsStats)(nil),    // 2: storagepb.ProposalsStats
	(*GetTotalsResponse)(nil), // 3: storagepb.GetTotalsResponse
}
var file_storagepb_stats_proto_depIdxs = []int32{
	1, // 0: storagepb.GetTotalsResponse.dao:type_name -> storagepb.DaoStats
	2, // 1: storagepb.GetTotalsResponse.proposals:type_name -> storagepb.ProposalsStats
	0, // 2: storagepb.Stats.GetTotals:input_type -> storagepb.GetTotalsRequest
	3, // 3: storagepb.Stats.GetTotals:output_type -> storagepb.GetTotalsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storagepb_stats_proto_init() }
func file_storagepb_stats_proto_init() {
	if File_storagepb_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storagepb_stats_proto_rawDesc), len(file_storagepb_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storagepb_stats_proto_goTypes,
		DependencyIndexes: file_storagepb_stats_proto_depIdxs,
		MessageInfos:      file_storagepb_stats_proto_msgTypes,
	}.Build()
	File_storagepb_stats_proto = out.File
	file_storagepb_stats_proto_goTypes = nil
	file_storagepb_stats_proto_depIdxs = nil
}
