// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: storagepb/vote.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VotesFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalIds   []string               `protobuf:"bytes,1,rep,name=proposal_ids,json=proposalIds,proto3" json:"proposal_ids,omitempty"`
	Voter         *string                `protobuf:"bytes,2,opt,name=voter,proto3,oneof" json:"voter,omitempty"`
	OrderByVoter  *string                `protobuf:"bytes,3,opt,name=order_by_voter,json=orderByVoter,proto3,oneof" json:"order_by_voter,omitempty"`
	Query         *string                `protobuf:"bytes,4,opt,name=query,proto3,oneof" json:"query,omitempty"`
	Limit         *uint64                `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *uint64                `protobuf:"varint,6,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	DaoId         *string                `protobuf:"bytes,7,opt,name=dao_id,json=daoId,proto3,oneof" json:"dao_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VotesFilterRequest) Reset() {
	*x = VotesFilterRequest{}
	mi := &file_storagepb_vote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VotesFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotesFilterRequest) ProtoMessage() {}

func (x *VotesFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotesFilterRequest.ProtoReflect.Descriptor instead.
func (*VotesFilterRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{0}
}

func (x *VotesFilterRequest) GetProposalIds() []string {
	if x != nil {
		return x.ProposalIds
	}
	return nil
}

func (x *VotesFilterRequest) GetVoter() string {
	if x != nil && x.Voter != nil {
		return *x.Voter
	}
	return ""
}

func (x *VotesFilterRequest) GetOrderByVoter() string {
	if x != nil && x.OrderByVoter != nil {
		return *x.OrderByVoter
	}
	return ""
}

func (x *VotesFilterRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *VotesFilterRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *VotesFilterRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *VotesFilterRequest) GetDaoId() string {
	if x != nil && x.DaoId != nil {
		return *x.DaoId
	}
	return ""
}

type VoteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ipfs          string                 `protobuf:"bytes,2,opt,name=ipfs,proto3" json:"ipfs,omitempty"`
	Voter         string                 `protobuf:"bytes,3,opt,name=voter,proto3" json:"voter,omitempty"`
	Created       uint64                 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	DaoId         string                 `protobuf:"bytes,5,opt,name=dao_id,json=daoId,proto3" json:"dao_id,omitempty"`
	ProposalId    string                 `protobuf:"bytes,6,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Choice        *anypb.Any             `protobuf:"bytes,7,opt,name=choice,proto3" json:"choice,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	App           string                 `protobuf:"bytes,9,opt,name=app,proto3" json:"app,omitempty"`
	Vp            float32                `protobuf:"fixed32,10,opt,name=vp,proto3" json:"vp,omitempty"`
	VpByStrategy  []float32              `protobuf:"fixed32,11,rep,packed,name=vp_by_strategy,json=vpByStrategy,proto3" json:"vp_by_strategy,omitempty"`
	VpState       string                 `protobuf:"bytes,12,opt,name=vp_state,json=vpState,proto3" json:"vp_state,omitempty"`
	EnsName       string                 `protobuf:"bytes,13,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteInfo) Reset() {
	*x = VoteInfo{}
	mi := &file_storagepb_vote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteInfo) ProtoMessage() {}

func (x *VoteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteInfo.ProtoReflect.Descriptor instead.
func (*VoteInfo) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{1}
}

func (x *VoteInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoteInfo) GetIpfs() string {
	if x != nil {
		return x.Ipfs
	}
	return ""
}

func (x *VoteInfo) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *VoteInfo) GetCreated() uint64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *VoteInfo) GetDaoId() string {
	if x != nil {
		return x.DaoId
	}
	return ""
}

func (x *VoteInfo) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *VoteInfo) GetChoice() *anypb.Any {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *VoteInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VoteInfo) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *VoteInfo) GetVp() float32 {
	if x != nil {
		return x.Vp
	}
	return 0
}

func (x *VoteInfo) GetVpByStrategy() []float32 {
	if x != nil {
		return x.VpByStrategy
	}
	return nil
}

func (x *VoteInfo) GetVpState() string {
	if x != nil {
		return x.VpState
	}
	return ""
}

func (x *VoteInfo) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

type VotesFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Votes         []*VoteInfo            `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalVp       float32                `protobuf:"fixed32,3,opt,name=total_vp,json=totalVp,proto3" json:"total_vp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VotesFilterResponse) Reset() {
	*x = VotesFilterResponse{}
	mi := &file_storagepb_vote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VotesFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotesFilterResponse) ProtoMessage() {}

func (x *VotesFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotesFilterResponse.ProtoReflect.Descriptor instead.
func (*VotesFilterResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{2}
}

func (x *VotesFilterResponse) GetVotes() []*VoteInfo {
	if x != nil {
		return x.Votes
	}
	return nil
}

func (x *VotesFilterResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *VotesFilterResponse) GetTotalVp() float32 {
	if x != nil {
		return x.TotalVp
	}
	return 0
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voter         string                 `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Proposal      string                 `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_storagepb_vote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateRequest) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *ValidateRequest) GetProposal() string {
	if x != nil {
		return x.Proposal
	}
	return ""
}

type ValidateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	VotingPower     float64                `protobuf:"fixed64,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	ValidationError *ValidationError       `protobuf:"bytes,3,opt,name=validation_error,json=validationError,proto3,oneof" json:"validation_error,omitempty"`
	VoteStatus      *VoteStatus            `protobuf:"bytes,4,opt,name=vote_status,json=voteStatus,proto3" json:"vote_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_storagepb_vote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateResponse) GetVotingPower() float64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *ValidateResponse) GetValidationError() *ValidationError {
	if x != nil {
		return x.ValidationError
	}
	return nil
}

func (x *ValidateResponse) GetVoteStatus() *VoteStatus {
	if x != nil {
		return x.VoteStatus
	}
	return nil
}

type VoteStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voted         bool                   `protobuf:"varint,1,opt,name=voted,proto3" json:"voted,omitempty"`
	Choice        *anypb.Any             `protobuf:"bytes,2,opt,name=choice,proto3" json:"choice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteStatus) Reset() {
	*x = VoteStatus{}
	mi := &file_storagepb_vote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteStatus) ProtoMessage() {}

func (x *VoteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteStatus.ProtoReflect.Descriptor instead.
func (*VoteStatus) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{5}
}

func (x *VoteStatus) GetVoted() bool {
	if x != nil {
		return x.Voted
	}
	return false
}

func (x *VoteStatus) GetChoice() *anypb.Any {
	if x != nil {
		return x.Choice
	}
	return nil
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          uint32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_storagepb_vote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{6}
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voter         string                 `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	Proposal      string                 `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	Choice        *anypb.Any             `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	Reason        *string                `protobuf:"bytes,6,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_storagepb_vote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareRequest) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *PrepareRequest) GetProposal() string {
	if x != nil {
		return x.Proposal
	}
	return ""
}

func (x *PrepareRequest) GetChoice() *anypb.Any {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *PrepareRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypedData     string                 `protobuf:"bytes,2,opt,name=typed_data,json=typedData,proto3" json:"typed_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_storagepb_vote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{8}
}

func (x *PrepareResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrepareResponse) GetTypedData() string {
	if x != nil {
		return x.TypedData
	}
	return ""
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sig           string                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_storagepb_vote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{9}
}

func (x *VoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoteRequest) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ipfs          string                 `protobuf:"bytes,2,opt,name=ipfs,proto3" json:"ipfs,omitempty"`
	Relayer       *Relayer               `protobuf:"bytes,3,opt,name=relayer,proto3" json:"relayer,omitempty"`
	ProposalId    string                 `protobuf:"bytes,4,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_storagepb_vote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{10}
}

func (x *VoteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoteResponse) GetIpfs() string {
	if x != nil {
		return x.Ipfs
	}
	return ""
}

func (x *VoteResponse) GetRelayer() *Relayer {
	if x != nil {
		return x.Relayer
	}
	return nil
}

func (x *VoteResponse) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

type Relayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Receipt       string                 `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relayer) Reset() {
	*x = Relayer{}
	mi := &file_storagepb_vote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relayer) ProtoMessage() {}

func (x *Relayer) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relayer.ProtoReflect.Descriptor instead.
func (*Relayer) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{11}
}

func (x *Relayer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Relayer) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

type DaosVotedInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voter         string                 `protobuf:"bytes,1,opt,name=voter,proto3" json:"voter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaosVotedInRequest) Reset() {
	*x = DaosVotedInRequest{}
	mi := &file_storagepb_vote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaosVotedInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaosVotedInRequest) ProtoMessage() {}

func (x *DaosVotedInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaosVotedInRequest.ProtoReflect.Descriptor instead.
func (*DaosVotedInRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{12}
}

func (x *DaosVotedInRequest) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

type DaosVotedInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaoIds        []string               `protobuf:"bytes,1,rep,name=dao_ids,json=daoIds,proto3" json:"dao_ids,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaosVotedInResponse) Reset() {
	*x = DaosVotedInResponse{}
	mi := &file_storagepb_vote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaosVotedInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaosVotedInResponse) ProtoMessage() {}

func (x *DaosVotedInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaosVotedInResponse.ProtoReflect.Descriptor instead.
func (*DaosVotedInResponse) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{13}
}

func (x *DaosVotedInResponse) GetDaoIds() []string {
	if x != nil {
		return x.DaoIds
	}
	return nil
}

func (x *DaosVotedInResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type VotesSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated_at,json=lastUpdatedAt,proto3,oneof" json:"last_updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VotesSubscribeRequest) Reset() {
	*x = VotesSubscribeRequest{}
	mi := &file_storagepb_vote_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VotesSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotesSubscribeRequest) ProtoMessage() {}

func (x *VotesSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_vote_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotesSubscribeRequest.ProtoReflect.Descriptor instead.
func (*VotesSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_storagepb_vote_proto_rawDescGZIP(), []int{14}
}

func (x *VotesSubscribeRequest) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

var File_storagepb_vote_proto protoreflect.FileDescriptor

const file_storagepb_vote_proto_rawDesc = "" +
	"\n" +
	"\x14storagepb/vote.proto\x12\tstoragepb\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x02\n" +
	"\x12VotesFilterRequest\x12!\n" +
	"\fproposal_ids\x18\x01 \x03(\tR\vproposalIds\x12\x19\n" +
	"\x05voter\x18\x02 \x01(\tH\x00R\x05voter\x88\x01\x01\x12)\n" +
	"\x0eorder_by_voter\x18\x03 \x01(\tH\x01R\forderByVoter\x88\x01\x01\x12\x19\n" +
	"\x05query\x18\x04 \x01(\tH\x02R\x05query\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\x04H\x03R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x06 \x01(\x04H\x04R\x06offset\x88\x01\x01\x12\x1a\n" +
	"\x06dao_id\x18\a \x01(\tH\x05R\x05daoId\x88\x01\x01B\b\n" +
	"\x06_voterB\x11\n" +
	"\x0f_order_by_voterB\b\n" +
	"\x06_queryB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\t\n" +
	"\a_dao_id\"\xda\x02\n" +
	"\bVoteInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04ipfs\x18\x02 \x01(\tR\x04ipfs\x12\x14\n" +
	"\x05voter\x18\x03 \x01(\tR\x05voter\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x04R\acreated\x12\x15\n" +
	"\x06dao_id\x18\x05 \x01(\tR\x05daoId\x12\x1f\n" +
	"\vproposal_id\x18\x06 \x01(\tR\n" +
	"proposalId\x12,\n" +
	"\x06choice\x18\a \x01(\v2\x14.google.protobuf.AnyR\x06choice\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x10\n" +
	"\x03app\x18\t \x01(\tR\x03app\x12\x0e\n" +
	"\x02vp\x18\n" +
	" \x01(\x02R\x02vp\x12$\n" +
	"\x0evp_by_strategy\x18\v \x03(\x02R\fvpByStrategy\x12\x19\n" +
	"\bvp_state\x18\f \x01(\tR\avpState\x12\x19\n" +
	"\bens_name\x18\r \x01(\tR\aensName\"|\n" +
	"\x13VotesFilterResponse\x12)\n" +
	"\x05votes\x18\x01 \x03(\v2\x13.storagepb.VoteInfoR\x05votes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x19\n" +
	"\btotal_vp\x18\x03 \x01(\x02R\atotalVp\"C\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05voter\x18\x01 \x01(\tR\x05voter\x12\x1a\n" +
	"\bproposal\x18\x02 \x01(\tR\bproposal\"\xde\x01\n" +
	"\x10ValidateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fvoting_power\x18\x02 \x01(\x01R\vvotingPower\x12J\n" +
	"\x10validation_error\x18\x03 \x01(\v2\x1a.storagepb.ValidationErrorH\x00R\x0fvalidationError\x88\x01\x01\x126\n" +
	"\vvote_status\x18\x04 \x01(\v2\x15.storagepb.VoteStatusR\n" +
	"voteStatusB\x13\n" +
	"\x11_validation_error\"P\n" +
	"\n" +
	"VoteStatus\x12\x14\n" +
	"\x05voted\x18\x01 \x01(\bR\x05voted\x12,\n" +
	"\x06choice\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06choice\"?\n" +
	"\x0fValidationError\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04code\"\x98\x01\n" +
	"\x0ePrepareRequest\x12\x14\n" +
	"\x05voter\x18\x01 \x01(\tR\x05voter\x12\x1a\n" +
	"\bproposal\x18\x02 \x01(\tR\bproposal\x12,\n" +
	"\x06choice\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x06choice\x12\x1b\n" +
	"\x06reason\x18\x06 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"@\n" +
	"\x0fPrepareResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"typed_data\x18\x02 \x01(\tR\ttypedData\"/\n" +
	"\vVoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\tR\x03sig\"\x81\x01\n" +
	"\fVoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04ipfs\x18\x02 \x01(\tR\x04ipfs\x12,\n" +
	"\arelayer\x18\x03 \x01(\v2\x12.storagepb.RelayerR\arelayer\x12\x1f\n" +
	"\vproposal_id\x18\x04 \x01(\tR\n" +
	"proposalId\"=\n" +
	"\aRelayer\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\areceipt\x18\x02 \x01(\tR\areceipt\"*\n" +
	"\x12DaosVotedInRequest\x12\x14\n" +
	"\x05voter\x18\x01 \x01(\tR\x05voter\"O\n" +
	"\x13DaosVotedInResponse\x12\x17\n" +
	"\adao_ids\x18\x01 \x03(\tR\x06daoIds\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"t\n" +
	"\x15VotesSubscribeRequest\x12G\n" +
	"\x0flast_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rlastUpdatedAt\x88\x01\x01B\x12\n" +
	"\x10_last_updated_at2\xad\x03\n" +
	"\x04Vote\x12I\n" +
	"\bGetVotes\x12\x1d.storagepb.VotesFilterRequest\x1a\x1e.storagepb.VotesFilterResponse\x12C\n" +
	"\bValidate\x12\x1a.storagepb.ValidateRequest\x1a\x1b.storagepb.ValidateResponse\x12@\n" +
	"\aPrepare\x12\x19.storagepb.PrepareRequest\x1a\x1a.storagepb.PrepareResponse\x127\n" +
	"\x04Vote\x12\x16.storagepb.VoteRequest\x1a\x17.storagepb.VoteResponse\x12O\n" +
	"\x0eGetDaosVotedIn\x12\x1d.storagepb.DaosVotedInRequest\x1a\x1e.storagepb.DaosVotedInResponse\x12I\n" +
	"\x0eVotesSubscribe\x12 .storagepb.VotesSubscribeRequest\x1a\x13.storagepb.VoteInfo0\x01B\rZ\v.;storagepbb\x06proto3"

var (
	file_storagepb_vote_proto_rawDescOnce sync.Once
	file_storagepb_vote_proto_rawDescData []byte
)

func file_storagepb_vote_proto_rawDescGZIP() []byte {
	file_storagepb_vote_proto_rawDescOnce.Do(func() {
		file_storagepb_vote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storagepb_vote_proto_rawDesc), len(file_storagepb_vote_proto_rawDesc)))
	})
	return file_storagepb_vote_proto_rawDescData
}

var file_storagepb_vote_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_storagepb_vote_proto_goTypes = []any{
	(*VotesFilterRequest)(nil),    // 0: storagepb.VotesFilterRequest
	(*VoteInfo)(nil),              // 1: storagepb.VoteInfo
	(*VotesFilterResponse)(nil),   // 2: storagepb.VotesFilterResponse
	(*ValidateRequest)(nil),       // 3: storagepb.ValidateRequest
	(*ValidateResponse)(nil),      // 4: storagepb.ValidateResponse
	(*VoteStatus)(nil),            // 5: storagepb.VoteStatus
	(*ValidationError)(nil),       // 6: storagepb.ValidationError
	(*PrepareRequest)(nil),        // 7: storagepb.PrepareRequest
	(*PrepareResponse)(nil),       // 8: storagepb.PrepareResponse
	(*VoteRequest)(nil),           // 9: storagepb.VoteRequest
	(*VoteResponse)(nil),          // 10: storagepb.VoteResponse
	(*Relayer)(nil),               // 11: storagepb.Relayer
	(*DaosVotedInRequest)(nil),    // 12: storagepb.DaosVotedInRequest
	(*DaosVotedInResponse)(nil),   // 13: storagepb.DaosVotedInResponse
	(*VotesSubscribeRequest)(nil), // 14: storagepb.VotesSubscribeRequest
	(*anypb.Any)(nil),             // 15: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_storagepb_vote_proto_depIdxs = []int32{
	15, // 0: storagepb.VoteInfo.choice:type_name -> google.protobuf.Any
	1,  // 1: storagepb.VotesFilterResponse.votes:type_name -> storagepb.VoteInfo
	6,  // 2: storagepb.ValidateResponse.validation_error:type_name -> storagepb.ValidationError
	5,  // 3: storagepb.ValidateResponse.vote_status:type_name -> storagepb.VoteStatus
	15, // 4: storagepb.VoteStatus.choice:type_name -> google.protobuf.Any
	15, // 5: storagepb.PrepareRequest.choice:type_name -> google.protobuf.Any
	11, // 6: storagepb.VoteResponse.relayer:type_name -> storagepb.Relayer
	16, // 7: storagepb.VotesSubscribeRequest.last_updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: storagepb.Vote.GetVotes:input_type -> storagepb.VotesFilterRequest
	3,  // 9: storagepb.Vote.Validate:input_type -> storagepb.ValidateRequest
	7,  // 10: storagepb.Vote.Prepare:input_type -> storagepb.PrepareRequest
	9,  // 11: storagepb.Vote.Vote:input_type -> storagepb.VoteRequest
	12, // 12: storagepb.Vote.GetDaosVotedIn:input_type -> storagepb.DaosVotedInRequest
	14, // 13: storagepb.Vote.VotesSubscribe:input_type -> storagepb.VotesSubscribeRequest
	2,  // 14: storagepb.Vote.GetVotes:output_type -> storagepb.VotesFilterResponse
	4,  // 15: storagepb.Vote.Validate:output_type -> storagepb.ValidateResponse
	8,  // 16: storagepb.Vote.Prepare:output_type -> storagepb.PrepareResponse
	10, // 17: storagepb.Vote.Vote:output_type -> storagepb.VoteResponse
	13, // 18: storagepb.Vote.GetDaosVotedIn:output_type -> storagepb.DaosVotedInResponse
	1,  // 19: storagepb.Vote.VotesSubscribe:output_type -> storagepb.VoteInfo
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_storagepb_vote_proto_init() }
func file_storagepb_vote_proto_init() {
	if File_storagepb_vote_proto != nil {
		return
	}
	file_storagepb_vote_proto_msgTypes[0].OneofWrappers = []any{}
	file_storagepb_vote_proto_msgTypes[4].OneofWrappers = []any{}
	file_storagepb_vote_proto_msgTypes[7].OneofWrappers = []any{}
	file_storagepb_vote_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storagepb_vote_proto_rawDesc), len(file_storagepb_vote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storagepb_vote_proto_goTypes,
		DependencyIndexes: file_storagepb_vote_proto_depIdxs,
		MessageInfos:      file_storagepb_vote_proto_msgTypes,
	}.Build()
	File_storagepb_vote_proto = out.File
	file_storagepb_vote_proto_goTypes = nil
	file_storagepb_vote_proto_depIdxs = nil
}
