create table public.daos
(
    id              text not null
        primary key,
    created_at      timestamp with time zone,
    updated_at      timestamp with time zone,
    name            text,
    private         boolean,
    about           text,
    avatar          text,
    terms           text,
    location        text,
    website         text,
    twitter         text,
    github          text,
    coingecko       text,
    email           text,
    network         text,
    symbol          text,
    skin            text,
    domain          text,
    strategies      jsonb,
    voting          jsonb,
    categories      jsonb,
    treasures       jsonb,
    followers_count integer,
    proposals_count integer,
    guidelines      text,
    template        text,
    parent_id       text
);

create table public.proposals
(
    id             text not null
        primary key,
    created_at     timestamp with time zone,
    updated_at     timestamp with time zone,
    ipfs           text,
    author         text,
    created        bigint,
    dao_id         text,
    network        text,
    symbol         text,
    type           text,
    strategies     jsonb,
    title          text,
    body           text,
    discussion     text,
    choices        jsonb,
    start          bigint,
    "end"          bigint,
    quorum         numeric,
    privacy        text,
    snapshot       text,
    state          text,
    link           text,
    app            text,
    scores         jsonb,
    scores_state   text,
    scores_total   numeric,
    scores_updated bigint,
    votes          bigint
);