// Code generated by MockGen. DO NOT EDIT.
// Source: internal/dao/service.go

// Package dao is a generated GoMock package.
package dao

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	proposal "github.com/goverland-labs/goverland-core-storage/internal/proposal"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishJSON mocks base method.
func (m *MockPublisher) PublishJSON(ctx context.Context, subject string, obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishJSON", ctx, subject, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishJSON indicates an expected call of PublishJSON.
func (mr *MockPublisherMockRecorder) PublishJSON(ctx, subject, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishJSON", reflect.TypeOf((*MockPublisher)(nil).PublishJSON), ctx, subject, obj)
}

// MockDataProvider is a mock of DataProvider interface.
type MockDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDataProviderMockRecorder
}

// MockDataProviderMockRecorder is the mock recorder for MockDataProvider.
type MockDataProviderMockRecorder struct {
	mock *MockDataProvider
}

// NewMockDataProvider creates a new mock instance.
func NewMockDataProvider(ctrl *gomock.Controller) *MockDataProvider {
	mock := &MockDataProvider{ctrl: ctrl}
	mock.recorder = &MockDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataProvider) EXPECT() *MockDataProviderMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataProvider) Create(dao Dao) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", dao)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataProviderMockRecorder) Create(dao interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataProvider)(nil).Create), dao)
}

// GetByFilters mocks base method.
func (m *MockDataProvider) GetByFilters(filters []Filter, count bool) (DaoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFilters", filters, count)
	ret0, _ := ret[0].(DaoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFilters indicates an expected call of GetByFilters.
func (mr *MockDataProviderMockRecorder) GetByFilters(filters, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFilters", reflect.TypeOf((*MockDataProvider)(nil).GetByFilters), filters, count)
}

// GetByID mocks base method.
func (m *MockDataProvider) GetByID(id uuid.UUID) (*Dao, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*Dao)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDataProviderMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDataProvider)(nil).GetByID), id)
}

// GetCategories mocks base method.
func (m *MockDataProvider) GetCategories() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockDataProviderMockRecorder) GetCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockDataProvider)(nil).GetCategories))
}

// Update mocks base method.
func (m *MockDataProvider) Update(dao Dao) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", dao)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataProviderMockRecorder) Update(dao interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataProvider)(nil).Update), dao)
}

// UpdateProposalCnt mocks base method.
func (m *MockDataProvider) UpdateProposalCnt(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProposalCnt", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProposalCnt indicates an expected call of UpdateProposalCnt.
func (mr *MockDataProviderMockRecorder) UpdateProposalCnt(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProposalCnt", reflect.TypeOf((*MockDataProvider)(nil).UpdateProposalCnt), id)
}

// MockDaoIDProvider is a mock of DaoIDProvider interface.
type MockDaoIDProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDaoIDProviderMockRecorder
}

// MockDaoIDProviderMockRecorder is the mock recorder for MockDaoIDProvider.
type MockDaoIDProviderMockRecorder struct {
	mock *MockDaoIDProvider
}

// NewMockDaoIDProvider creates a new mock instance.
func NewMockDaoIDProvider(ctrl *gomock.Controller) *MockDaoIDProvider {
	mock := &MockDaoIDProvider{ctrl: ctrl}
	mock.recorder = &MockDaoIDProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaoIDProvider) EXPECT() *MockDaoIDProviderMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockDaoIDProvider) GetAll() ([]DaoID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]DaoID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDaoIDProviderMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDaoIDProvider)(nil).GetAll))
}

// GetOrCreate mocks base method.
func (m *MockDaoIDProvider) GetOrCreate(originID string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", originID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockDaoIDProviderMockRecorder) GetOrCreate(originID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockDaoIDProvider)(nil).GetOrCreate), originID)
}

// MockUniqueVoterProvider is a mock of UniqueVoterProvider interface.
type MockUniqueVoterProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUniqueVoterProviderMockRecorder
}

// MockUniqueVoterProviderMockRecorder is the mock recorder for MockUniqueVoterProvider.
type MockUniqueVoterProviderMockRecorder struct {
	mock *MockUniqueVoterProvider
}

// NewMockUniqueVoterProvider creates a new mock instance.
func NewMockUniqueVoterProvider(ctrl *gomock.Controller) *MockUniqueVoterProvider {
	mock := &MockUniqueVoterProvider{ctrl: ctrl}
	mock.recorder = &MockUniqueVoterProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniqueVoterProvider) EXPECT() *MockUniqueVoterProviderMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockUniqueVoterProvider) BatchCreate(arg0 []UniqueVoter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockUniqueVoterProviderMockRecorder) BatchCreate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockUniqueVoterProvider)(nil).BatchCreate), arg0)
}

// UpdateVotersCount mocks base method.
func (m *MockUniqueVoterProvider) UpdateVotersCount() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVotersCount")
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVotersCount indicates an expected call of UpdateVotersCount.
func (mr *MockUniqueVoterProviderMockRecorder) UpdateVotersCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVotersCount", reflect.TypeOf((*MockUniqueVoterProvider)(nil).UpdateVotersCount))
}

// MockProposalProvider is a mock of ProposalProvider interface.
type MockProposalProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProposalProviderMockRecorder
}

// MockProposalProviderMockRecorder is the mock recorder for MockProposalProvider.
type MockProposalProviderMockRecorder struct {
	mock *MockProposalProvider
}

// NewMockProposalProvider creates a new mock instance.
func NewMockProposalProvider(ctrl *gomock.Controller) *MockProposalProvider {
	mock := &MockProposalProvider{ctrl: ctrl}
	mock.recorder = &MockProposalProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProposalProvider) EXPECT() *MockProposalProviderMockRecorder {
	return m.recorder
}

// GetEarliestByDaoID mocks base method.
func (m *MockProposalProvider) GetEarliestByDaoID(arg0 uuid.UUID) (*proposal.Proposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEarliestByDaoID", arg0)
	ret0, _ := ret[0].(*proposal.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEarliestByDaoID indicates an expected call of GetEarliestByDaoID.
func (mr *MockProposalProviderMockRecorder) GetEarliestByDaoID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEarliestByDaoID", reflect.TypeOf((*MockProposalProvider)(nil).GetEarliestByDaoID), arg0)
}
